# Copyright 2026 Firefly Software Foundation.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# Author: Firefly Software Foundation
# SPDX-License-Identifier: Apache-2.0

"""The frozen run summary, run step and run log wire contract."""

import json
from pathlib import Path
from typing import get_args
from uuid import UUID

import pytest
from pydantic import ValidationError

from firefly_weave.contracts import run_views
from firefly_weave.contracts.run_views import (
    FailedStep,
    RunListQuery,
    RunLogEntry,
    RunLogPage,
    RunLogQuery,
    RunStepQuery,
    RunSummary,
    RunSummaryActivation,
    RunSummaryCaller,
    RunSummaryPage,
    RunSummaryQuery,
    RunSummaryWorkflow,
    StepFact,
    StepFactPage,
    StepFactWithOutput,
)

RUN = "0b9c6f7e-3c55-4d6b-9a51-4f1b0c2d7e01"
SUMMARY = {
    "id": RUN,
    "workflow": {
        "name": "invoice-approval",
        "version": "1.3.0",
        "definition_version_id": "6a1f0c34-1d4e-4c1b-8f0a-2b3c4d5e6f70",
    },
    "activation_id": "7b2e1d45-2e5f-4d2c-9a1b-3c4d5e6f7a81",
    "activation": {"name": "invoice-approval", "revision": 4},
    "status": "running",
    "paused": False,
    "test": False,
    "origin": "webhook",
    "caller": None,
    "retried_from_run_id": None,
    "started_at": "2026-10-07T12:00:00Z",
    "updated_at": "2026-10-07T12:00:05Z",
    "ended_at": None,
    "duration_ms": None,
    "business_key": "INV-1042",
    "correlation_key": None,
    "failed_step": None,
    "active_incidents": 0,
    "archived": False,
}
STEP = {
    "node_id": "send",
    "instance_key": "send[3]",
    "iteration": [3],
    "kind": "action",
    "status": "failed",
    "scheduled_at": "2026-10-07T12:00:01Z",
    "started_at": "2026-10-07T12:00:02Z",
    "ended_at": "2026-10-07T12:00:03Z",
    "duration_ms": 1000,
    "queue_wait_ms": 1000,
    "attempts": 3,
    "worker_id": None,
    "error_code": "SMTP_REJECTED",
    "child_run_id": None,
    "log_entries": 2,
}
LOG = {
    "id": "8c3f2e56-3f60-4e3d-8b2c-4d5e6f7a8b92",
    "at": "2026-10-07T12:00:02Z",
    "source": "ai",
    "level": "info",
    "code": "AI.USAGE",
    "message": "AI turn finished",
    "node_id": "support",
    "instance_key": "support#2",
    "attempt": 1,
    "worker_id": None,
    "fields": {"input_tokens": 812, "output_tokens": 96},
    "redactions": 0,
    "truncated": False,
}
# The shared instance-key cases, generated by scripts/language_fixtures.py from firefly_weave.contracts.instance_keys.
INSTANCE_KEYS = Path(__file__).resolve().parents[2] / "studio/tests/fixtures/language/instance-keys.json"
SHARED_KEYS = json.loads(INSTANCE_KEYS.read_text(encoding="utf-8"))
# Step IDs are ResourceName values, so the synthetic engine nodes (@join:…, @branch:…) never appear in a view.
STEP_KEYS = [case for case in SHARED_KEYS["valid"] if not case["node_id"].startswith("@")]


def parse(model, value):
    return model.model_validate_json(json.dumps(value))


def test_field_names_and_order_are_frozen():
    assert list(RunSummaryWorkflow.model_fields) == ["name", "version", "definition_version_id"]
    assert list(RunSummaryActivation.model_fields) == ["name", "revision"]
    assert list(RunSummaryCaller.model_fields) == ["run_id", "node_id", "instance_key"]
    assert list(FailedStep.model_fields) == ["node_id", "instance_key", "error_code"]
    assert list(RunSummary.model_fields) == [
        "id",
        "workflow",
        "activation_id",
        "activation",
        "status",
        "paused",
        "test",
        "origin",
        "caller",
        "retried_from_run_id",
        "started_at",
        "updated_at",
        "ended_at",
        "duration_ms",
        "business_key",
        "correlation_key",
        "failed_step",
        "active_incidents",
        "archived",
        "handled_errors",
    ]
    assert list(StepFact.model_fields) == [
        "node_id",
        "instance_key",
        "iteration",
        "kind",
        "status",
        "scheduled_at",
        "started_at",
        "ended_at",
        "duration_ms",
        "queue_wait_ms",
        "attempts",
        "worker_id",
        "error_code",
        "child_run_id",
        "log_entries",
        "omissions",
        "handled",
    ]
    assert list(StepFactWithOutput.model_fields) == [*StepFact.model_fields, "output"]
    assert list(RunLogEntry.model_fields) == [
        "id",
        "at",
        "source",
        "level",
        "code",
        "message",
        "node_id",
        "instance_key",
        "attempt",
        "worker_id",
        "fields",
        "redactions",
        "truncated",
    ]
    assert list(RunSummaryPage.model_fields) == ["items", "next_cursor"]
    assert list(StepFactPage.model_fields) == ["items", "next_cursor", "complete"]
    assert list(RunLogPage.model_fields) == ["items", "next_cursor"]
    assert list(RunSummaryQuery.model_fields) == [
        "workflow",
        "version",
        "status",
        "origin",
        "started_after",
        "started_before",
        "include_test",
        "caller_run_id",
        "top_level_only",
        "retried_from_run_id",
        "business_key",
        "correlation_key",
        "has_active_incident",
        "has_handled_errors",
        "include_archived",
        "activation_id",
        "order",
        "limit",
        "cursor",
    ]
    assert list(RunStepQuery.model_fields) == ["step", "include", "limit", "cursor"]
    assert list(RunLogQuery.model_fields) == ["level", "source", "node_id", "limit", "cursor"]


def test_vocabularies_are_frozen():
    assert get_args(run_views.RunOrigin.__value__) == (
        "manual",
        "webhook",
        "schedule",
        "broker",
        "email",
        "provider",
        "retry",
        "call",
        "test",
    )
    assert get_args(run_views.RunStatus.__value__) == (
        "queued",
        "running",
        "waiting",
        "suspended",
        "succeeded",
        "failed",
        "cancelled",
        "timed_out",
    )
    assert get_args(run_views.RunSummaryOrder.__value__) == ("started_desc", "started_asc", "updated_desc")
    assert get_args(run_views.StepStatus.__value__) == (
        "scheduled",
        "running",
        "waiting",
        "succeeded",
        "failed",
        "cancelled",
        "timed_out",
    )
    assert len(get_args(run_views.StepKind.__value__)) == 13
    assert get_args(run_views.LogSource.__value__) == ("engine", "worker", "connector", "ai")
    assert get_args(run_views.LogLevel.__value__) == run_views.LOG_LEVELS == ("debug", "info", "warning", "error")


def test_spec_example_round_trips_and_unavailable_items_keep_their_shape():
    assert parse(RunSummary, SUMMARY).model_dump(mode="json") == SUMMARY
    unavailable = {
        "id": "9d4a3f67-4a71-4f4e-9c3d-5e6f7a8b9ca3",
        "unavailable": True,
        "omissions": [{"path": "", "reason": "classification_unavailable"}],
    }
    page = parse(RunSummaryPage, {"items": [SUMMARY, unavailable], "next_cursor": None})
    assert [type(item).__name__ for item in page.items] == ["RunSummary", "UnavailableResource"]
    assert page.model_dump(mode="json") == {"items": [SUMMARY, unavailable], "next_cursor": None}


@pytest.mark.parametrize(
    "change",
    [
        {"status": "succeeded"},
        {"ended_at": "2026-10-07T12:00:09Z", "duration_ms": 9000},
        {"origin": "call"},
        {"caller": {"run_id": RUN, "node_id": "notify", "instance_key": ""}},
        {"origin": "retry"},
        {"retried_from_run_id": RUN},
        {"origin": "test"},
        {"failed_step": {"node_id": "send", "instance_key": "send[3]", "error_code": "SMTP_REJECTED"}},
        {"updated_at": "2026-10-07T11:59:59Z"},
        {"business_key": "x" * 201},
        {"status": "canceled"},
        {"origin": "manually"},
        {"parent_run_id": RUN},
    ],
)
def test_incoherent_or_unknown_summaries_are_rejected(change):
    with pytest.raises(ValidationError):
        parse(RunSummary, {**SUMMARY, **change})


def test_terminal_children_retries_and_test_runs_are_accepted():
    ended = {"ended_at": "2026-10-07T12:00:09Z", "duration_ms": 9000}
    failed = {
        **SUMMARY,
        **ended,
        "status": "failed",
        "failed_step": {"node_id": "send", "instance_key": "send[3]", "error_code": None},
    }
    child = {
        **SUMMARY,
        "origin": "call",
        "test": True,
        "caller": {"run_id": RUN, "node_id": "notify", "instance_key": "notify[2]"},
    }
    retry = {**SUMMARY, **ended, "status": "succeeded", "origin": "retry", "retried_from_run_id": RUN}
    test = {
        **SUMMARY,
        "origin": "test",
        "test": True,
        "workflow": {**SUMMARY["workflow"], "version": "1.3.0+test.7b2e1d452e5f"},
    }
    legacy = {**SUMMARY, "origin": None}
    for value in (failed, child, retry, test, legacy):
        assert parse(RunSummary, value).model_dump(mode="json") == value


def test_step_output_is_absent_null_value_or_omitted():
    returned_null = {**STEP, "output": None}
    returned = {**STEP, "output": {"accepted": False}}
    omitted = {**STEP, "omissions": [{"path": "/output", "reason": "classified_secret"}]}
    page = parse(
        StepFactPage, {"items": [STEP, returned_null, returned, omitted], "next_cursor": None, "complete": False}
    )
    assert [type(item).__name__ for item in page.items] == [
        "StepFact",
        "StepFactWithOutput",
        "StepFactWithOutput",
        "StepFact",
    ]
    assert page.model_dump(mode="json")["items"] == [STEP, returned_null, returned, omitted]
    with pytest.raises(ValidationError):
        parse(StepFactWithOutput, {**returned, "omissions": omitted["omissions"]})


@pytest.mark.parametrize(
    "change",
    [
        {"instance_key": "send"},
        {"instance_key": "other[3]"},
        {"iteration": [2]},
        {"iteration": []},
        {"instance_key": "send[03]"},
        {"node_id": "@join:send"},
        {"duration_ms": None},
        {"queue_wait_ms": None},
        {"started_at": None},
        {"kind": "subprocess"},
        {"status": "completed"},
    ],
)
def test_incoherent_steps_are_rejected(change):
    with pytest.raises(ValidationError):
        parse(StepFact, {**STEP, **change})


def test_pre_upgrade_steps_have_no_timings():
    legacy = {
        **STEP,
        "instance_key": "",
        "iteration": [],
        "status": "succeeded",
        "scheduled_at": None,
        "started_at": None,
        "ended_at": None,
        "duration_ms": None,
        "queue_wait_ms": None,
        "attempts": 0,
        "error_code": None,
        "log_entries": 0,
    }
    assert parse(StepFact, legacy).model_dump(mode="json") == legacy


def test_log_entries_carry_ai_usage_and_engine_rules():
    assert parse(RunLogEntry, LOG).model_dump(mode="json") == LOG
    engine = {
        **LOG,
        "source": "engine",
        "code": "task_completed",
        "message": "",
        "attempt": None,
        "fields": {},
        "node_id": None,
        "instance_key": "",
    }
    assert parse(RunLogEntry, engine).model_dump(mode="json") == engine
    for change in (
        {"source": "worker"},
        {"fields": {"input_tokens": True, "output_tokens": 96}},
        {"fields": {"input_tokens": 812}},
        {"node_id": None, "instance_key": ""},
    ):
        with pytest.raises(ValidationError):
            parse(RunLogEntry, {**LOG, **change})
    for change in (
        {"attempt": 1},
        {"instance_key": "support#2"},
        {"fields": {f"k{index}": "v" for index in range(17)}},
        {"message": "x" * 513},
    ):
        with pytest.raises(ValidationError):
            parse(RunLogEntry, {**engine, **change})


@pytest.mark.parametrize("case", STEP_KEYS, ids=lambda case: case["key"])
def test_step_facts_follow_c11_for_every_shared_key(case):
    view = case["view"]
    fact = {**STEP, "node_id": view["node_id"], "instance_key": view["instance_key"], "iteration": view["iteration"]}
    assert parse(StepFact, fact).model_dump(mode="json") == fact
    with pytest.raises(ValidationError):
        parse(StepFact, {**fact, "iteration": [*view["iteration"], 0]})


@pytest.mark.parametrize("case", [case for case in SHARED_KEYS["invalid"] if case["key"]], ids=lambda case: case["key"])
def test_views_reject_every_shared_non_canonical_key(case):
    for model, value in (
        (FailedStep, {"node_id": "send", "instance_key": case["key"], "error_code": None}),
        (StepFact, {**STEP, "instance_key": case["key"], "iteration": []}),
    ):
        with pytest.raises(ValidationError):
            parse(model, value)


@pytest.mark.parametrize(
    "query",
    [
        {"version": "1.3.0"},
        {"top_level_only": True, "caller_run_id": RUN},
        {"top_level_only": True, "origin": "call"},
        {"origin": "test"},
        {"started_after": "2026-10-07T12:00:00Z", "started_before": "2026-10-07T12:00:00Z"},
        {"started_after": "2025-08-01T00:00:00Z", "started_before": "2026-10-07T00:00:00Z"},
    ],
)
def test_contradictory_filters_are_filter_errors(query):
    with pytest.raises(ValidationError) as failure:
        parse(RunSummaryQuery, query)
    assert [item["type"] for item in failure.value.errors()] == ["weave_filter"]


@pytest.mark.parametrize(
    "query",
    [
        {"status": ["running"] * 9},
        {"status": ["canceled"]},
        {"started_after": "2026-10-07T12:00:00"},
        # Offsets that push the UTC instant past year 9999 or before year 1 are bad values, not server errors.
        {"started_after": "9999-12-31T23:59:59-23:59"},
        {"started_before": "9999-12-31T23:59:59-01:00"},
        {"started_after": "0001-01-01T00:00:00+23:59"},
        {"started_before": "0001-01-01T00:00:00+00:01"},
        {"limit": 0},
        {"limit": 101},
        {"workflow": "bad name"},
        {"cursor": "not/base64"},
    ],
)
def test_invalid_values_are_validation_errors(query):
    with pytest.raises(ValidationError) as failure:
        parse(RunSummaryQuery, query)
    assert "weave_filter" not in {item["type"] for item in failure.value.errors()}


def test_summary_cursor_collection_is_canonical_and_bound_to_every_filter_and_the_order():
    base = parse(
        RunSummaryQuery, {"workflow": "invoice-approval", "include_test": True, "status": ["running", "failed"]}
    )
    same = parse(
        RunSummaryQuery,
        {
            "workflow": "invoice-approval",
            "include_test": True,
            "status": ["failed", "running", "failed"],
            "limit": 10,
            "cursor": "abc",
        },
    )
    assert base.status == ["failed", "running"]
    assert base.cursor_collection() == same.cursor_collection()
    assert base.cursor_collection().endswith(":started_desc")
    local = parse(RunSummaryQuery, {"started_after": "2026-10-07T14:00:00+02:00"})
    assert (
        local.cursor_collection()
        == parse(RunSummaryQuery, {"started_after": "2026-10-07T12:00:00Z"}).cursor_collection()
    )
    changes = {
        "workflow": "other",
        "version": "1.3.0",
        "status": ["failed"],
        "origin": "webhook",
        "started_after": "2026-10-01T00:00:00Z",
        "started_before": "2026-10-08T00:00:00Z",
        "include_test": False,
        "caller_run_id": RUN,
        "retried_from_run_id": RUN,
        "business_key": "INV-1042",
        "correlation_key": "thread",
        "has_active_incident": True,
        "include_archived": True,
        "activation_id": RUN,
        "order": "updated_desc",
    }
    for name, value in changes.items():
        changed = parse(RunSummaryQuery, {**base.model_dump(mode="json"), name: value})
        assert changed.cursor_collection() != base.cursor_collection(), name
    top = parse(RunSummaryQuery, {"top_level_only": True})
    assert top.cursor_collection() != parse(RunSummaryQuery, {}).cursor_collection()


def test_step_and_log_queries_bound_their_pages_and_take_static_step_ids():
    run_id, other_run_id = UUID(RUN), UUID(SUMMARY["activation_id"])
    assert RunStepQuery().limit == RunLogQuery().limit == 200
    assert parse(RunStepQuery, {"limit": 500, "include": "output", "step": "send"}).limit == 500
    for query in ({"limit": 501}, {"step": "send[3]"}, {"include": "input"}):
        with pytest.raises(ValidationError):
            parse(RunStepQuery, query)
    for query in ({"limit": 501}, {"node_id": "support#2"}, {"level": "trace"}, {"source": "runner"}):
        with pytest.raises(ValidationError):
            parse(RunLogQuery, query)
    steps = parse(RunStepQuery, {"step": "send"}).cursor_collection(run_id)
    assert steps == parse(RunStepQuery, {"step": "send", "include": "output"}).cursor_collection(run_id)
    assert steps != parse(RunStepQuery, {}).cursor_collection(run_id)
    assert steps != parse(RunStepQuery, {"step": "send"}).cursor_collection(other_run_id)
    logs = parse(RunLogQuery, {"level": "warning"}).cursor_collection(run_id)
    assert logs != parse(RunLogQuery, {"level": "error"}).cursor_collection(run_id)
    assert logs != parse(RunLogQuery, {"level": "warning", "node_id": "send"}).cursor_collection(run_id)
    assert logs != parse(RunLogQuery, {"level": "warning", "source": "ai"}).cursor_collection(run_id)


@pytest.mark.parametrize("handled", ["continue", "errorOutput"])
def test_handled_field_requires_failed_status(handled):
    with pytest.raises(ValidationError):
        parse(StepFact, {**STEP, "status": "succeeded", "handled": handled})
    assert parse(StepFact, {**STEP, "handled": handled}).handled == handled
    assert "handled" not in parse(StepFact, STEP).model_dump(mode="json")


def test_handled_summary_default_is_omitted_and_nonzero_round_trips():
    assert "handled_errors" not in parse(RunSummary, SUMMARY).model_dump(mode="json")
    value = {**SUMMARY, "handled_errors": 2}
    assert parse(RunSummary, value).model_dump(mode="json") == value
    with pytest.raises(ValidationError):
        parse(RunSummary, {**SUMMARY, "handled_errors": -1})


@pytest.mark.parametrize(
    "change",
    [
        {"duration_ms": -1},
        {"queue_wait_ms": -1},
        {"ended_at": "2026-10-07T12:00:01Z"},
        {"scheduled_at": "2026-10-07T12:00:03Z"},
    ],
)
def test_step_timings_cannot_be_negative_or_reversed(change):
    with pytest.raises(ValidationError):
        parse(StepFact, {**STEP, **change})


QUERY_CHANGES = {
    "workflow": "other",
    "version": "1.3.0",
    "status": ["failed"],
    "origin": "webhook",
    "started_after": "2026-10-01T00:00:00Z",
    "started_before": "2026-10-08T00:00:00Z",
    "include_test": True,
    "caller_run_id": RUN,
    "top_level_only": True,
    "retried_from_run_id": RUN,
    "business_key": "INV-1042",
    "correlation_key": "thread",
    "has_active_incident": True,
    "has_handled_errors": True,
    "include_archived": True,
    "activation_id": RUN,
    "order": "updated_desc",
}


@pytest.mark.parametrize("model", [RunSummaryQuery, RunListQuery])
@pytest.mark.parametrize("field,value", QUERY_CHANGES.items())
def test_every_run_query_field_binds_the_cursor(model, field, value):
    base = parse(model, {"workflow": "invoice-approval"})
    changed = parse(model, {**base.model_dump(mode="json"), field: value})
    assert changed.cursor_collection() != base.cursor_collection()


def test_query_digest_coverage_includes_every_filter():
    assert set(QUERY_CHANGES) == set(RunSummaryQuery.model_fields) - {"limit", "cursor"}
    plain = RunSummaryQuery()
    assert plain.cursor_collection() != plain.model_copy(update={"has_handled_errors": True}).cursor_collection()
    assert plain.cursor_collection() != plain.model_copy(update={"has_handled_errors": False}).cursor_collection()
    with pytest.raises(ValidationError):
        parse(RunSummaryQuery, {"order": "id"})
    assert RunListQuery().order == "started_desc"
    assert RunListQuery(order="id").order == "id"
    assert RunListQuery().cursor_collection().startswith("runs:")
    assert RunListQuery().cursor_collection() != plain.cursor_collection()
    assert (
        parse(RunListQuery, {"status": ["running", "failed", "running"]}).cursor_collection()
        == parse(RunListQuery, {"status": ["failed", "running"], "limit": 1, "cursor": "abc"}).cursor_collection()
    )


@pytest.mark.parametrize(
    "value",
    [
        1791374400,
        True,
        {},
        [],
        "1791374400",
        "2026-10-07 12:00:00Z",
        "2026-10-07T12:00:00",
        "2026-10-07T12:00Z",
        "2026-10-07T12:00:00+00:60",
        "2027-02-29T00:00:00Z",
        "2026-10-07T12:00:00." + "1" * 64 + "Z",
    ],
)
def test_query_timestamps_require_bounded_rfc3339(value):
    with pytest.raises(ValidationError):
        parse(RunSummaryQuery, {"started_after": value})


@pytest.mark.parametrize(
    "value,expected",
    [
        ("2028-02-29T00:00:00Z", "2028-02-29T00:00:00+00:00"),
        ("2026-10-07T12:00:00+23:59", "2026-10-06T12:01:00+00:00"),
        ("2026-10-07t12:00:00z", "2026-10-07T12:00:00+00:00"),
    ],
)
def test_query_timestamps_normalize_valid_leap_days_and_offsets(value, expected):
    assert parse(RunSummaryQuery, {"started_after": value}).started_after.isoformat() == expected


def test_time_range_accepts_exactly_four_hundred_days():
    query = {"started_after": "2026-01-01T00:00:00Z", "started_before": "2027-02-05T00:00:00Z"}
    assert parse(RunSummaryQuery, query).started_before is not None
    for before in ["2027-02-05T00:00:00.000001Z", "2025-12-31T23:59:59Z"]:
        with pytest.raises(ValidationError):
            parse(RunSummaryQuery, {**query, "started_before": before})


def test_run_list_surface_uses_one_typed_query():
    from firefly_weave.contracts.openapi import export_openapi
    from firefly_weave.contracts.schema_export import export_schemas
    from firefly_weave.contracts.surface import OPERATIONS

    operation = OPERATIONS["runs.list"]
    assert operation.query is RunListQuery
    parameters = export_openapi()["paths"][operation.canonical_path]["get"]["parameters"]
    names = [item["name"] for item in parameters if item["in"] == "query"]
    assert names == list(RunListQuery.model_fields)
    assert export_schemas()["run-list-query"]["$defs"]["RunListOrder"]["enum"] == [
        "id",
        "started_desc",
        "started_asc",
        "updated_desc",
    ]
