/*
Copyright 2026 Firefly Software Foundation.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
Author: Firefly Software Foundation
SPDX-License-Identifier: Apache-2.0
*/
// The shared language fixtures, generated by scripts/language_fixtures.py. The
// platform formats numbers for concat and join exactly as JavaScript's
// String(x), so Studio previews match it.
import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import { describe, expect, it } from "vitest";

const fixture = (name: string) =>
  JSON.parse(
    readFileSync(
      resolve(import.meta.dirname, "fixtures/language", name),
      "utf8",
    ),
  );

describe("shared language fixtures", () => {
  it("formats every concat and join value as JavaScript does", () => {
    const { cases } = fixture("text-conversion.json") as {
      cases: { value: string | number | boolean; text: string }[];
    };
    expect(cases.length).toBeGreaterThan(10);
    for (const { value, text } of cases) expect(String(value), text).toBe(text);
  });
  it("accepts exactly the valid instance keys with the published pattern", () => {
    const { pattern, valid, invalid } = fixture("instance-keys.json") as {
      pattern: string;
      valid: { key: string; node_id: string }[];
      invalid: { key: string }[];
    };
    const instanceKey = new RegExp(`^(?:${pattern})$`, "u");
    for (const { key, node_id } of valid) {
      expect(instanceKey.test(key), key).toBe(true);
      expect(key.startsWith(node_id), key).toBe(true);
      expect(node_id, key).not.toMatch(/[[\]#~]/);
    }
    for (const { key } of invalid)
      expect(instanceKey.test(key), key).toBe(false);
    expect(invalid.length).toBeGreaterThan(10);
  });
  it("maps every concat to template segments and saves them normalized", () => {
    type Expression = Record<string, unknown>;
    type Segment =
      | { kind: "text"; text: string }
      | { kind: "placeholder"; expression: Expression };
    const { cases } = fixture("template-segments.json") as {
      cases: {
        name: string;
        expression: Expression;
        segments: Segment[] | null;
        saved: Expression | null;
      }[];
    };
    expect(cases.length).toBeGreaterThan(8);
    const isText = (value: unknown): value is { literal: string } =>
      typeof value === "object" &&
      value !== null &&
      Object.keys(value).length === 1 &&
      typeof (value as { literal?: unknown }).literal === "string";
    for (const { name, expression, segments, saved } of cases) {
      const op = (expression as { op?: { name?: string; args?: unknown[] } })
        .op;
      if (segments === null) {
        expect(op?.name === "concat", name).toBe(false);
        expect(saved, name).toBeNull();
        continue;
      }
      // One segment per concat argument: string literals are text, anything else a placeholder.
      expect(
        segments.map((segment) => segment.kind),
        name,
      ).toEqual(
        (op?.args ?? []).map((arg) => (isText(arg) ? "text" : "placeholder")),
      );
      // Saving merges adjacent text, drops empty text and stores text-only templates as one literal.
      const args = (saved as { op?: { args: unknown[] } }).op?.args;
      if (args === undefined) {
        expect(saved, name).toEqual({
          literal: segments
            .map((segment) => (segment.kind === "text" ? segment.text : ""))
            .join(""),
        });
        continue;
      }
      args.forEach((arg, index) => {
        expect(arg, name).not.toEqual({ literal: "" });
        if (index > 0)
          expect(isText(arg) && isText(args[index - 1]), name).toBe(false);
      });
    }
  });
  it("publishes the manifest with Studio marks on every entry", () => {
    const { manifest } = fixture("manifest.json") as {
      manifest: Record<string, { studio: string }[]>;
    };
    for (const group of ["step_kinds", "operators", "workflow_fields"])
      for (const entry of manifest[group])
        expect(["ready", "pending"]).toContain(entry.studio);
  });
});
