/*
Copyright 2026 Firefly Software Foundation.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
Author: Firefly Software Foundation
SPDX-License-Identifier: Apache-2.0
*/
// Composes the Firefly Weave lockup and the Firefly icon files from a local
// checkout of the private Firefly Brand Kit. Run it from the kit's root (the
// kit resolves its fonts relative to the working directory):
//
//   node <weave>/scripts/brand/weave-lockup.mjs --out <weave>
//
// No kit code is copied into Weave: the kit's logo and type modules are
// imported from the working directory at run time, and only the generated
// files are written. The construction is the approved one in the brand
// foundation design: the compact Firefly logo, a hairline separator 1X after
// the chevron apex, and "Weave" in Manrope 500 1X after the separator, where
// 1X is the Firefly x-height (108 drawing units).
import { copyFileSync, existsSync, mkdirSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { pathToFileURL } from "node:url";
import { parseArgs } from "node:util";

const { values } = parseArgs({
  options: {
    out: { type: "string" },
    favicons: { type: "string", default: "dist/Firefly-Brand-Kit/02-Logo/favicon" },
  },
});
if (!values.out || !existsSync(join(values.out, "studio/package.json")))
  throw Error("Pass --out <a Firefly Weave checkout>.");
if (!existsSync("scripts/logo.mjs"))
  throw Error("Run this from the root of a Firefly Brand Kit checkout: ./scripts/logo.mjs is missing.");

const kit = (path) => import(pathToFileURL(resolve(path)).href);
const { geometry, placed, svg, icon } = await kit("scripts/logo.mjs");
const { face, line } = await kit("scripts/lib/type.mjs");

const X = 108;
const PAPER = "#f3f1eb";
const CHARCOAL = "#10110f";
const r = (v) => Math.round(v * 100) / 100;
const NOTICE =
  "<!-- Firefly marks: trademarks and proprietary artwork of Firefly Software Solutions Inc., " +
  "used in Firefly Weave by the Firefly Software Foundation with permission. Not licensed under " +
  "the Apache License 2.0; see NOTICE. Generated by scripts/brand/weave-lockup.mjs; do not edit. -->\n";

/** Adds role, title and desc to a drawing's root without touching the drawing. */
function accessible(drawing, title, desc) {
  const open = drawing.indexOf(">", drawing.indexOf("<svg")) + 1;
  const root = drawing
    .slice(0, open - 1)
    .replace("<svg ", '<svg role="img" aria-labelledby="title desc" ');
  return `${NOTICE}${root}><title id="title">${title}</title><desc id="desc">${desc}</desc>${drawing.slice(open)}\n`;
}

/** The lockup in drawing units, with its measurements. */
function lockup({ ink, solid }) {
  const [x0, top, FW, FH] = geometry().compact;
  const logo = svg({ ink, slogan: false, solid, title: "", id: "weave-lockup-trail" });
  const sx = x0 + FW - 1 + X;
  const half = (1.25 * FH) / 2;
  const [y0, y1] = [-54 - half, -54 + half];
  const separator = `<path d="M${r(sx)} ${r(y0)}V${r(y1)}" stroke="${ink}" stroke-width="${r(0.04 * X)}" stroke-opacity="0.55" stroke-linecap="butt"/>`;
  const font = face(500);
  const size = font.unitsPerEm * 0.1;
  const tracking = -45 / font.unitsPerEm;
  const scale = size / font.unitsPerEm;
  const run = font.layout("Weave");
  const first = run.glyphs[0].bbox.minX * scale;
  const x = sx + X - first;
  let cursor = x;
  run.positions.slice(0, -1).forEach((p) => (cursor += p.xAdvance * scale + tracking * size));
  const right = cursor + run.positions.at(-1).xOffset * scale + run.glyphs.at(-1).bbox.maxX * scale;
  const word = line("Weave", { x, y: 0, size, weight: 500, tracking, fill: ink });
  const box = [x0, r(y0 - 1), r(right + 1 - x0), r(y1 - y0 + 2)];
  const drawing = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="${box.join(" ")}">${placed(logo, x0, top, FW)}${separator}${word}</svg>`;
  return { drawing, FW, width: box[2], height: box[3] };
}

const colorway = (ink) => (ink === PAPER ? "paper" : "charcoal");
const files = {};
for (const [name, ink, solid] of [
  ["weave-lockup-reversed", PAPER, false],
  ["weave-lockup-color", CHARCOAL, false],
  ["weave-lockup-small-reversed", PAPER, true],
]) {
  const { drawing, FW, width, height } = lockup({ ink, solid });
  files[`assets/brand/${name}.svg`] = accessible(
    drawing,
    "Firefly Weave",
    `The Firefly logo${solid ? " with a solid chevron" : ""}, a hairline separator and the word Weave, in ${colorway(ink)} on a transparent background.`,
  );
  console.log(
    `${name}: FW ${r(FW)}, width ${width}, height ${height}, FW/width ${(FW / width).toFixed(4)}, Firefly part at 200px ${r((FW / width) * 200)}px`,
  );
}
const tile = (options, id) => icon(options).replaceAll("icon-trail", id);
files["assets/brand/firefly-icon.svg"] = accessible(
  tile({}, "firefly-icon-trail"),
  "Firefly",
  "The Firefly icon: the amber spark and chevron with its light trail on a charcoal rounded tile.",
);
files["assets/brand/firefly-icon-small.svg"] = accessible(
  tile({ solid: true }, "firefly-icon-small-trail"),
  "Firefly",
  "The Firefly icon for small sizes: the amber spark and a solid chevron on a charcoal rounded tile.",
);
files["assets/brand/firefly-mark.svg"] = accessible(
  tile({ background: "none" }, "firefly-mark-trail"),
  "Firefly",
  "The Firefly mark: the amber spark and chevron with its light trail on a transparent background.",
);
for (const name of ["weave-lockup-reversed", "weave-lockup-small-reversed", "firefly-mark"])
  files[`studio/public/assets/${name}.svg`] = files[`assets/brand/${name}.svg`];
files["studio/public/favicon.svg"] = files["assets/brand/firefly-icon.svg"];

for (const [path, text] of Object.entries(files)) {
  const target = join(values.out, path);
  mkdirSync(dirname(target), { recursive: true });
  writeFileSync(target, text);
}
for (const name of ["favicon.ico", "apple-touch-icon.png"]) {
  const source = join(values.favicons, name);
  if (!existsSync(source))
    throw Error(`Missing ${source}: run "npm run build -- --only logo" in the kit first.`);
  copyFileSync(source, join(values.out, "studio/public", name));
}
console.log(`Wrote ${Object.keys(files).length + 2} files under ${resolve(values.out)}.`);
