/*
Copyright 2026 Firefly Software Foundation.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
Author: Firefly Software Foundation
SPDX-License-Identifier: Apache-2.0
*/
// Composes the Firefly Weave lockup and the Firefly icon files from a local
// checkout of the private Firefly Brand Kit. Run it from the kit's root (the
// kit resolves its fonts relative to the working directory):
//
//   node <weave>/scripts/brand/weave-lockup.mjs --out <weave>
//
// No kit code is copied into Weave: the kit's logo and type modules are
// imported from the working directory at run time, and only the generated
// files are written. The construction is the approved one in the brand
// foundation design: the compact Firefly logo, a hairline separator 1X after
// the chevron apex, and the weave wordmark 1X after the separator, where 1X is
// the Firefly x-height (108 drawing units). The wordmark comes from its
// committed masters, assets/brand/weave-wordmark.svg and, for the small
// lockup, weave-wordmark-small.svg; no lockup sets live or outlined type.
import { copyFileSync, existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { createRequire } from "node:module";
import { dirname, join, resolve } from "node:path";
import { pathToFileURL } from "node:url";
import { parseArgs } from "node:util";

const { values } = parseArgs({
  options: {
    out: { type: "string" },
    favicons: { type: "string", default: "dist/Firefly-Brand-Kit/02-Logo/favicon" },
  },
});
if (!values.out || !existsSync(join(values.out, "studio/package.json")))
  throw Error("Pass --out <a Firefly Weave checkout>.");
if (!existsSync("scripts/logo.mjs"))
  throw Error("Run this from the root of a Firefly Brand Kit checkout: ./scripts/logo.mjs is missing.");

const kit = (path) => import(pathToFileURL(resolve(path)).href);
const { geometry, placed, svg, icon } = await kit("scripts/logo.mjs");
const { face, line } = await kit("scripts/lib/type.mjs");

const X = 108;
const PAPER = "#f3f1eb";
const CHARCOAL = "#10110f";
// The woven w's strand: amber on charcoal, gold on paper (amber is 1.58:1 on paper).
const AMBER = "#ffb34a";
const GOLD = "#855414";
const r = (v) => Math.round(v * 100) / 100;
const NOTICE =
  "<!-- Firefly marks: trademarks and proprietary artwork of Firefly Software Solutions Inc., " +
  "used in Firefly Weave by the Firefly Software Foundation with permission. Not licensed under " +
  "the Apache License 2.0; see NOTICE. Generated by scripts/brand/weave-lockup.mjs; do not edit. -->\n";
// Files that contain the lockup also carry the weave wordmark, a Foundation trademark.
const LOCKUP_NOTICE = NOTICE.replace(
  "Generated by",
  "The weave wordmark is a trademark of the Firefly Software Foundation. Generated by",
);

/** Adds the notice, role, title and desc to a drawing's root without touching the drawing. */
function accessible(drawing, title, desc, notice = NOTICE) {
  const open = drawing.indexOf(">", drawing.indexOf("<svg")) + 1;
  const root = drawing
    .slice(0, open - 1)
    .replace("<svg ", '<svg role="img" aria-labelledby="title desc" ');
  return `${notice}${root}><title id="title">${title}</title><desc id="desc">${desc}</desc>${drawing.slice(open)}\n`;
}

/** Reads a weave wordmark master: its ink and strand paths and its right ink edge. */
function wordmark(name) {
  const file = join(values.out, "assets/brand", `${name}.svg`);
  const text = readFileSync(file, "utf8");
  const part = (role) => {
    const found = text.match(new RegExp(`<path class="weave-${role}" d="([MLQZ0-9. -]+)"`));
    if (!found) throw Error(`${file}: no weave-${role} path in absolute M, L, Q and Z commands.`);
    return found[1];
  };
  const [ink, thread] = [part("ink"), part("thread")];
  // Every command uses x y pairs, so even-numbered values are x (control points included).
  const xs = (d) => [...d.matchAll(/-?\d+(?:\.\d+)?/g)].map(Number).filter((_, i) => i % 2 === 0);
  return { ink, thread, right: Math.max(...xs(ink), ...xs(thread)) };
}

/** Moves absolute path data right by dx, leaving y untouched. */
function moveRight(d, dx) {
  let index = 0;
  return d.replace(/-?\d+(?:\.\d+)?/g, (n) => String(index++ % 2 ? Number(n) : r(Number(n) + dx)));
}

/** The lockup in drawing units, with its measurements. */
function lockup({ ink, solid }) {
  const [x0, top, FW, FH] = geometry().compact;
  const logo = svg({ ink, slogan: false, solid, title: "", id: "weave-lockup-trail" });
  const sx = x0 + FW - 1 + X;
  const half = (1.25 * FH) / 2;
  const [y0, y1] = [-54 - half, -54 + half];
  const separator = `<path d="M${r(sx)} ${r(y0)}V${r(y1)}" stroke="${ink}" stroke-width="${r(0.04 * X)}" stroke-opacity="0.55" stroke-linecap="butt"/>`;
  // The wordmark's w starts 1X after the separator, on the Firefly baseline.
  const mark = wordmark(solid ? "weave-wordmark-small" : "weave-wordmark");
  const x = sx + X;
  const strand = ink === PAPER ? AMBER : GOLD;
  const word =
    `<path class="weave-ink" d="${moveRight(mark.ink, x)}" fill="${ink}"/>` +
    `<path class="weave-thread" d="${moveRight(mark.thread, x)}" fill="${strand}"/>`;
  const box = [x0, r(y0 - 1), r(x + mark.right + 1 - x0), r(y1 - y0 + 2)];
  const drawing = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="${box.join(" ")}">${placed(logo, x0, top, FW)}${separator}${word}</svg>`;
  return { drawing, FW, width: box[2], height: box[3] };
}

const colorway = (ink) => (ink === PAPER ? "paper" : "charcoal");
const files = {};
for (const [name, ink, solid] of [
  ["weave-lockup-reversed", PAPER, false],
  ["weave-lockup-color", CHARCOAL, false],
  ["weave-lockup-small-reversed", PAPER, true],
]) {
  const { drawing, FW, width, height } = lockup({ ink, solid });
  files[`assets/brand/${name}.svg`] = accessible(
    drawing,
    "Firefly Weave",
    `The Firefly logo${solid ? " with a solid chevron" : ""}, a hairline separator and the weave wordmark, its w woven from two strands, in ${colorway(ink)} with ${ink === PAPER ? "an amber" : "a gold"} strand, on a transparent background.`,
    LOCKUP_NOTICE,
  );
  console.log(
    `${name}: FW ${r(FW)}, width ${width}, height ${height}, FW/width ${(FW / width).toFixed(4)}, Firefly part at 192px ${r((FW / width) * 192)}px`,
  );
}
const tile = (options, id) => icon(options).replaceAll("icon-trail", id);
files["assets/brand/firefly-icon.svg"] = accessible(
  tile({}, "firefly-icon-trail"),
  "Firefly",
  "The Firefly icon: the amber spark and chevron with its light trail on a charcoal rounded tile.",
);
files["assets/brand/firefly-icon-small.svg"] = accessible(
  tile({ solid: true }, "firefly-icon-small-trail"),
  "Firefly",
  "The Firefly icon for small sizes: the amber spark and a solid chevron on a charcoal rounded tile.",
);
files["assets/brand/firefly-mark.svg"] = accessible(
  tile({ background: "none" }, "firefly-mark-trail"),
  "Firefly",
  "The Firefly mark: the amber spark and chevron with its light trail on a transparent background.",
);
for (const name of ["weave-lockup-reversed", "weave-lockup-small-reversed", "firefly-mark"])
  files[`studio/public/assets/${name}.svg`] = files[`assets/brand/${name}.svg`];
files["studio/public/favicon.svg"] = files["assets/brand/firefly-icon.svg"];

// The README banner, the social preview, the DMG window, the launch page's
// lockup, the macOS icon master and the Windows icon. They reuse the lockup and
// icon above, so every Firefly artwork file comes from this one construction.
const sharp = (await import(pathToFileURL(createRequire(resolve("package.json")).resolve("sharp")).href)).default;
const STONE = "#bfb8ab";
const GRAPHITE = "#474a42";
const RAISED = "#1f201c";
const RULE = "#2e2f2a";
const PLATE = "#767672";
const reversed = lockup({ ink: PAPER, solid: false });

/** The reversed lockup over the descriptor line, centered vertically on charcoal. */
function hero({ width, height, x, centered }) {
  const k = x / X; // Pixels per drawing unit when 1X is x pixels.
  const [lockupWidth, lockupHeight] = [reversed.width * k, reversed.height * k];
  const size = (28 * x) / 32; // 28 px when 1X is 32 px.
  const regular = face(400);
  const cap = (regular.capHeight * size) / regular.unitsPerEm;
  const top = (height - (lockupHeight + x + cap)) / 2;
  const left = centered ? (width - lockupWidth) / 2 : 2 * x;
  const descriptor = line("Workflow orchestration and integration", {
    x: centered ? width / 2 : left + k,
    y: top + lockupHeight + x + cap,
    size,
    weight: 400,
    fill: STONE,
    anchor: centered ? "middle" : "start",
  });
  const logo = placed(reversed.drawing, r(left), r(top), r(lockupWidth));
  return `<svg xmlns="http://www.w3.org/2000/svg" width="${width}" height="${height}" viewBox="0 0 ${width} ${height}"><rect width="${width}" height="${height}" fill="${CHARCOAL}"/>${logo}${descriptor}</svg>`;
}

/** The DMG window, 720 x 440 at 1x; Finder draws 128 px icons at (190, 236) and (530, 236). */
function dmgBackground() {
  const x = Math.max(16, Math.ceil((80 * X) / reversed.FW)); // The Firefly part stays at least 80 px wide.
  const k = x / X;
  const text = (value, options) => line(value, { weight: 400, ...options });
  const drop = (cx) => `<circle cx="${cx}" cy="236" r="74" fill="${RAISED}" stroke="${GRAPHITE}" stroke-width="1"/>`;
  // Finder colors icon labels by appearance; black (4.60) and white (4.56) both read on this plate.
  const plate = (cx, w) => `<rect x="${cx - w / 2}" y="308" width="${w}" height="26" rx="6" fill="${PLATE}"/>`;
  return [
    `<svg xmlns="http://www.w3.org/2000/svg" width="720" height="440" viewBox="0 0 720 440">`,
    `<rect width="720" height="440" fill="${CHARCOAL}"/>`,
    placed(reversed.drawing, 40, 32, r(reversed.width * k)),
    text("Drag Firefly Weave Studio into Applications to install.", {
      x: 40,
      y: r(32 + reversed.height * k + 34),
      size: 17,
      weight: 500,
      fill: PAPER,
    }),
    drop(190),
    drop(530),
    plate(190, 196),
    plate(530, 132),
    `<path d="M304 236H416M401 223L416 236L401 249" fill="none" stroke="${AMBER}" stroke-width="3" stroke-linecap="round" stroke-linejoin="round"/>`,
    `<path d="M40 362H680" stroke="${RULE}"/>`,
    text("Then open Firefly Weave Studio from Applications.", { x: 40, y: 394, size: 15, fill: PAPER }),
    text("Firefly Software Foundation", { x: 40, y: 418, size: 12, fill: STONE }),
    `</svg>`,
  ].join("");
}

/** Rasterize a drawing to exact pixels: supersample with sharp, then downscale. */
async function png(drawing, width, height = width) {
  const viewBox = drawing.match(/viewBox="([^"]+)"/)[1].split(/\s+/).map(Number);
  const intrinsic = Number(drawing.match(/^<svg[^>]*\swidth="([\d.]+)"/)?.[1] ?? viewBox[2]);
  const density = (72 * width * (width < 64 ? 8 : 4)) / intrinsic;
  const big = await sharp(Buffer.from(drawing), { density }).png().toBuffer();
  return sharp(big).resize(width, height, { kernel: "lanczos3" }).png({ compressionLevel: 9 }).toBuffer();
}

/** An ICO container with PNG entries, which Windows Vista and later read at every size. */
function ico(images) {
  const header = Buffer.alloc(6 + 16 * images.length);
  header.writeUInt16LE(0, 0);
  header.writeUInt16LE(1, 2);
  header.writeUInt16LE(images.length, 4);
  let offset = header.length;
  images.forEach(({ size, data }, index) => {
    const at = 6 + 16 * index;
    header.writeUInt8(size >= 256 ? 0 : size, at);
    header.writeUInt8(size >= 256 ? 0 : size, at + 1);
    header.writeUInt16LE(1, at + 4);
    header.writeUInt16LE(32, at + 6);
    header.writeUInt32LE(data.length, at + 8);
    header.writeUInt32LE(offset, at + 12);
    offset += data.length;
  });
  return Buffer.concat([header, ...images.map((image) => image.data)]);
}

// Windows icon entries: the solid chevron below 32 px, the trail from 32 px up (the kit's rule).
const ICO_ENTRIES = [
  [16, tile({ solid: true }, "ico-small-trail")],
  [24, tile({ solid: true }, "ico-small-trail")],
  [32, tile({}, "ico-trail")],
  [48, tile({}, "ico-trail")],
  [64, tile({}, "ico-trail")],
  [256, tile({}, "ico-trail")],
];
const macosIcon = `<svg xmlns="http://www.w3.org/2000/svg" width="1024" height="1024" viewBox="0 0 1024 1024">${placed(tile({}, "macos-icon-trail"), 100, 100, 824)}</svg>`;
const banner = hero({ width: 1120, height: 280, x: 32, centered: false });
const dmg = dmgBackground();
files["assets/banner.svg"] = accessible(
  banner,
  "Firefly Weave — workflow orchestration and integration",
  "The Firefly Weave logo in paper above the line Workflow orchestration and integration in stone, on charcoal.",
  LOCKUP_NOTICE,
);
files["desktop/artwork/dmg-background.svg"] = accessible(
  dmg,
  "Install Firefly Weave Studio",
  "Drag the app on the left into Applications on the right, then open Firefly Weave Studio from Applications.",
  LOCKUP_NOTICE,
);
// The desktop launch page shows the same lockup from its own folder (the app's CSP allows img-src 'self').
files["desktop/bootstrap/weave-lockup-reversed.svg"] = files["assets/brand/weave-lockup-reversed.svg"];
files["desktop/artwork/app-icon-macos.svg"] = accessible(
  macosIcon,
  "Firefly Weave Studio",
  "The Firefly icon tile at 824 by 824 pixels on a transparent 1024 by 1024 canvas, the macOS icon grid.",
);
files["desktop/artwork/dmg-background.png"] = await png(dmg, 720, 440);
files["assets/brand/social-preview.png"] = await png(hero({ width: 1280, height: 640, x: 48, centered: true }), 1280, 640);
files["desktop/src-tauri/icons/icon.ico"] = ico(
  await Promise.all(ICO_ENTRIES.map(async ([size, drawing]) => ({ size, data: await png(drawing, size) }))),
);

for (const [path, text] of Object.entries(files)) {
  const target = join(values.out, path);
  mkdirSync(dirname(target), { recursive: true });
  writeFileSync(target, text);
}
for (const name of ["favicon.ico", "apple-touch-icon.png"]) {
  const source = join(values.favicons, name);
  if (!existsSync(source))
    throw Error(`Missing ${source}: run "npm run build -- --only logo" in the kit first.`);
  copyFileSync(source, join(values.out, "studio/public", name));
}
console.log(`Wrote ${Object.keys(files).length + 2} files under ${resolve(values.out)}.`);
