/*
Generated by studio/scripts/build-icons.mjs from lucide-static 1.52.0
(https://lucide.dev). Do not edit: change iconMap in the script and run
`npm run icons`. Icon geometry: Copyright (c) 2026 Lucide Icons and
Contributors, ISC License; icons derived from Feather: Copyright (c)
2013-present Cole Bemis, MIT License. Full text:
studio/public/licenses/lucide-LICENSE.txt.
*/
export type IconTag =
  | "path"
  | "circle"
  | "rect"
  | "line"
  | "polyline"
  | "polygon"
  | "ellipse";
export type IconAttribute =
  | "d"
  | "cx"
  | "cy"
  | "r"
  | "x"
  | "y"
  | "width"
  | "height"
  | "rx"
  | "ry"
  | "x1"
  | "y1"
  | "x2"
  | "y2"
  | "points";
export interface IconNode {
  readonly tag: IconTag;
  readonly attrs: Readonly<Partial<Record<IconAttribute, string>>>;
}
/** Weave icon name → the Lucide icon it draws. */
export const lucideNames = {
  home: "house",
  workflows: "workflow",
  runs: "circle-play",
  tasks: "clipboard-check",
  email: "mail",
  connections: "plug",
  operations: "network",
  workers: "cpu",
  settings: "settings",
  workspace: "layers",
  user: "user-round",
  template: "layout-template",
  assistant: "messages-square",
  action: "zap",
  decisionTable: "table",
  llm: "sparkles",
  transform: "braces",
  switch: "split",
  parallel: "git-fork",
  wait: "hourglass",
  signal: "radio-tower",
  humanTask: "user-round-check",
  fail: "octagon-x",
  play: "play",
  plus: "plus",
  search: "search",
  chevron: "chevron-right",
  undo: "undo-2",
  redo: "redo-2",
  fit: "scan",
  source: "code-xml",
  check: "check",
  download: "download",
  upload: "upload",
  trash: "trash",
  menu: "menu",
  more: "ellipsis",
  close: "x",
  save: "save",
  lock: "lock",
  external: "external-link",
  copy: "copy",
  refresh: "refresh-cw",
  warning: "triangle-alert",
  help: "circle-question-mark",
  logout: "log-out",
  cloud: "cloud",
  laptop: "laptop",
  panel: "panel-right",
  tidy: "layout-grid",
  failCircle: "circle-x",
  manualTrigger: "mouse-pointer-click",
  webhook: "webhook",
  schedule: "calendar-clock",
  kafka: "inbox",
  appEvent: "app-window",
  calledTrigger: "square-arrow-down-right",
  agent: "bot",
  model: "brain-circuit",
  tools: "wrench",
  memory: "database",
  output: "file-output",
  forEach: "iteration-cw",
  callWorkflow: "square-stack",
  textTemplate: "text-cursor-input",
  execute: "flask-conical",
  pin: "pin",
  unpin: "pin-off",
  stale: "clock-alert",
  breakpoint: "circle-dot",
  runHistory: "history",
  stickyNote: "sticky-note",
  minimap: "map",
  zoomIn: "zoom-in",
  zoomOut: "zoom-out",
  drag: "grip-vertical",
  spinner: "loader-circle",
  edit: "pencil",
  docs: "book-open",
  expand: "maximize-2",
  chevronLeft: "chevron-left",
  chevronDown: "chevron-down",
  schemaView: "list-tree",
  tableView: "table-2",
  jsonView: "file-braces",
  typeText: "type",
  typeNumber: "hash",
  typeBoolean: "toggle-left",
  typeList: "list",
  typeObject: "box",
  typeDate: "calendar",
  typeFile: "file",
  typeAny: "circle-dashed",
  overview: "gauge",
  clusters: "server",
  metrics: "chart-line",
  logs: "scroll-text",
  alerts: "bell",
  alertFiring: "bell-ring",
  incidents: "siren",
  approvals: "stamp",
  compose: "container",
  kubernetes: "ship-wheel",
  drain: "circle-pause",
  revoke: "ban",
  critical: "octagon-alert",
  info: "info",
  degraded: "circle-alert",
  ok: "circle-check",
  off: "circle-off",
} as const;
export type IconName = keyof typeof lucideNames;
/** Each icon's elements, in Lucide's order, on a 24 × 24 grid. */
export const iconNodes: Readonly<Record<IconName, readonly IconNode[]>> = {
  home: [
    { tag: "path", attrs: { d: "M15 21v-8a1 1 0 0 0-1-1h-4a1 1 0 0 0-1 1v8" } },
    {
      tag: "path",
      attrs: {
        d: "M3 10a2 2 0 0 1 .709-1.528l7-6a2 2 0 0 1 2.582 0l7 6A2 2 0 0 1 21 10v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z",
      },
    },
  ],
  workflows: [
    {
      tag: "rect",
      attrs: { width: "8", height: "8", x: "3", y: "3", rx: "2" },
    },
    { tag: "path", attrs: { d: "M7 11v4a2 2 0 0 0 2 2h4" } },
    {
      tag: "rect",
      attrs: { width: "8", height: "8", x: "13", y: "13", rx: "2" },
    },
  ],
  runs: [
    {
      tag: "path",
      attrs: {
        d: "M9 9.003a1 1 0 0 1 1.517-.859l4.997 2.997a1 1 0 0 1 0 1.718l-4.997 2.997A1 1 0 0 1 9 14.996z",
      },
    },
    { tag: "circle", attrs: { cx: "12", cy: "12", r: "10" } },
  ],
  tasks: [
    {
      tag: "rect",
      attrs: { width: "8", height: "4", x: "8", y: "2", rx: "1", ry: "1" },
    },
    {
      tag: "path",
      attrs: {
        d: "M16 4h2a2 2 0 0 1 2 2v14a2 2 0 0 1-2 2H6a2 2 0 0 1-2-2V6a2 2 0 0 1 2-2h2",
      },
    },
    { tag: "path", attrs: { d: "m9 14 2 2 4-4" } },
  ],
  email: [
    { tag: "path", attrs: { d: "m22 7-8.991 5.727a2 2 0 0 1-2.009 0L2 7" } },
    {
      tag: "rect",
      attrs: { x: "2", y: "4", width: "20", height: "16", rx: "2" },
    },
  ],
  connections: [
    { tag: "path", attrs: { d: "M12 22v-5" } },
    { tag: "path", attrs: { d: "M15 8V2" } },
    {
      tag: "path",
      attrs: {
        d: "M17 8a1 1 0 0 1 1 1v4a4 4 0 0 1-4 4h-4a4 4 0 0 1-4-4V9a1 1 0 0 1 1-1z",
      },
    },
    { tag: "path", attrs: { d: "M9 8V2" } },
  ],
  operations: [
    {
      tag: "rect",
      attrs: { x: "16", y: "16", width: "6", height: "6", rx: "1" },
    },
    {
      tag: "rect",
      attrs: { x: "2", y: "16", width: "6", height: "6", rx: "1" },
    },
    {
      tag: "rect",
      attrs: { x: "9", y: "2", width: "6", height: "6", rx: "1" },
    },
    { tag: "path", attrs: { d: "M5 16v-3a1 1 0 0 1 1-1h12a1 1 0 0 1 1 1v3" } },
    { tag: "path", attrs: { d: "M12 12V8" } },
  ],
  workers: [
    { tag: "path", attrs: { d: "M12 20v2" } },
    { tag: "path", attrs: { d: "M12 2v2" } },
    { tag: "path", attrs: { d: "M17 20v2" } },
    { tag: "path", attrs: { d: "M17 2v2" } },
    { tag: "path", attrs: { d: "M2 12h2" } },
    { tag: "path", attrs: { d: "M2 17h2" } },
    { tag: "path", attrs: { d: "M2 7h2" } },
    { tag: "path", attrs: { d: "M20 12h2" } },
    { tag: "path", attrs: { d: "M20 17h2" } },
    { tag: "path", attrs: { d: "M20 7h2" } },
    { tag: "path", attrs: { d: "M7 20v2" } },
    { tag: "path", attrs: { d: "M7 2v2" } },
    {
      tag: "rect",
      attrs: { x: "4", y: "4", width: "16", height: "16", rx: "2" },
    },
    {
      tag: "rect",
      attrs: { x: "8", y: "8", width: "8", height: "8", rx: "1" },
    },
  ],
  settings: [
    {
      tag: "path",
      attrs: {
        d: "M9.671 4.136a2.34 2.34 0 0 1 4.659 0 2.34 2.34 0 0 0 3.319 1.915 2.34 2.34 0 0 1 2.33 4.033 2.34 2.34 0 0 0 0 3.831 2.34 2.34 0 0 1-2.33 4.033 2.34 2.34 0 0 0-3.319 1.915 2.34 2.34 0 0 1-4.659 0 2.34 2.34 0 0 0-3.32-1.915 2.34 2.34 0 0 1-2.33-4.033 2.34 2.34 0 0 0 0-3.831A2.34 2.34 0 0 1 6.35 6.051a2.34 2.34 0 0 0 3.319-1.915",
      },
    },
    { tag: "circle", attrs: { cx: "12", cy: "12", r: "3" } },
  ],
  workspace: [
    {
      tag: "path",
      attrs: {
        d: "M12.83 2.18a2 2 0 0 0-1.66 0L2.6 6.08a1 1 0 0 0 0 1.83l8.58 3.91a2 2 0 0 0 1.66 0l8.58-3.9a1 1 0 0 0 0-1.83z",
      },
    },
    {
      tag: "path",
      attrs: {
        d: "M2 12a1 1 0 0 0 .58.91l8.6 3.91a2 2 0 0 0 1.65 0l8.58-3.9A1 1 0 0 0 22 12",
      },
    },
    {
      tag: "path",
      attrs: {
        d: "M2 17a1 1 0 0 0 .58.91l8.6 3.91a2 2 0 0 0 1.65 0l8.58-3.9A1 1 0 0 0 22 17",
      },
    },
  ],
  user: [
    { tag: "circle", attrs: { cx: "12", cy: "8", r: "5" } },
    { tag: "path", attrs: { d: "M20 21a8 8 0 0 0-16 0" } },
  ],
  template: [
    {
      tag: "rect",
      attrs: { width: "18", height: "7", x: "3", y: "3", rx: "1" },
    },
    {
      tag: "rect",
      attrs: { width: "9", height: "7", x: "3", y: "14", rx: "1" },
    },
    {
      tag: "rect",
      attrs: { width: "5", height: "7", x: "16", y: "14", rx: "1" },
    },
  ],
  assistant: [
    {
      tag: "path",
      attrs: {
        d: "M16 10a2 2 0 0 1-2 2H6.828a2 2 0 0 0-1.414.586l-2.202 2.202A.71.71 0 0 1 2 14.286V4a2 2 0 0 1 2-2h10a2 2 0 0 1 2 2z",
      },
    },
    {
      tag: "path",
      attrs: {
        d: "M20 9a2 2 0 0 1 2 2v10.286a.71.71 0 0 1-1.212.502l-2.202-2.202A2 2 0 0 0 17.172 19H10a2 2 0 0 1-2-2v-1",
      },
    },
  ],
  action: [
    {
      tag: "path",
      attrs: {
        d: "M15.914 4a1.5 1.5 0 00-2.474-1.561l-9 9A1.5 1.5 0 005.5 14h4.002a.5.5 0 01.471.666L8.086 20a1.5 1.5 0 002.475 1.56l9-9A1.5 1.5 0 0018.5 10h-3.997a.5.5 0 01-.472-.667z",
      },
    },
  ],
  decisionTable: [
    { tag: "path", attrs: { d: "M12 3v18" } },
    {
      tag: "rect",
      attrs: { width: "18", height: "18", x: "3", y: "3", rx: "2" },
    },
    { tag: "path", attrs: { d: "M3 9h18" } },
    { tag: "path", attrs: { d: "M3 15h18" } },
  ],
  llm: [
    {
      tag: "path",
      attrs: {
        d: "M11.017 2.814a1 1 0 0 1 1.966 0l1.051 5.558a2 2 0 0 0 1.594 1.594l5.558 1.051a1 1 0 0 1 0 1.966l-5.558 1.051a2 2 0 0 0-1.594 1.594l-1.051 5.558a1 1 0 0 1-1.966 0l-1.051-5.558a2 2 0 0 0-1.594-1.594l-5.558-1.051a1 1 0 0 1 0-1.966l5.558-1.051a2 2 0 0 0 1.594-1.594z",
      },
    },
    { tag: "path", attrs: { d: "M20 2v4" } },
    { tag: "path", attrs: { d: "M22 4h-4" } },
    { tag: "circle", attrs: { cx: "4", cy: "20", r: "2" } },
  ],
  transform: [
    {
      tag: "path",
      attrs: {
        d: "M8 3H7a2 2 0 0 0-2 2v5a2 2 0 0 1-2 2 2 2 0 0 1 2 2v5c0 1.1.9 2 2 2h1",
      },
    },
    {
      tag: "path",
      attrs: {
        d: "M16 21h1a2 2 0 0 0 2-2v-5c0-1.1.9-2 2-2a2 2 0 0 1-2-2V5a2 2 0 0 0-2-2h-1",
      },
    },
  ],
  switch: [
    { tag: "path", attrs: { d: "M16 3h5v5" } },
    { tag: "path", attrs: { d: "M8 3H3v5" } },
    { tag: "path", attrs: { d: "M12 22v-8.3a4 4 0 0 0-1.172-2.872L3 3" } },
    { tag: "path", attrs: { d: "m15 9 6-6" } },
  ],
  parallel: [
    { tag: "circle", attrs: { cx: "12", cy: "18", r: "3" } },
    { tag: "circle", attrs: { cx: "6", cy: "6", r: "3" } },
    { tag: "circle", attrs: { cx: "18", cy: "6", r: "3" } },
    { tag: "path", attrs: { d: "M18 9v2c0 .6-.4 1-1 1H7c-.6 0-1-.4-1-1V9" } },
    { tag: "path", attrs: { d: "M12 12v3" } },
  ],
  wait: [
    { tag: "path", attrs: { d: "M5 22h14" } },
    { tag: "path", attrs: { d: "M5 2h14" } },
    {
      tag: "path",
      attrs: {
        d: "M17 22v-4.172a2 2 0 0 0-.586-1.414L12 12l-4.414 4.414A2 2 0 0 0 7 17.828V22",
      },
    },
    {
      tag: "path",
      attrs: {
        d: "M7 2v4.172a2 2 0 0 0 .586 1.414L12 12l4.414-4.414A2 2 0 0 0 17 6.172V2",
      },
    },
  ],
  signal: [
    { tag: "path", attrs: { d: "M4.9 16.1C1 12.2 1 5.8 4.9 1.9" } },
    { tag: "path", attrs: { d: "M7.8 4.7a6.14 6.14 0 0 0-.8 7.5" } },
    { tag: "circle", attrs: { cx: "12", cy: "9", r: "2" } },
    { tag: "path", attrs: { d: "M16.2 4.8c2 2 2.26 5.11.8 7.47" } },
    { tag: "path", attrs: { d: "M19.1 1.9a9.96 9.96 0 0 1 0 14.1" } },
    { tag: "path", attrs: { d: "M9.5 18h5" } },
    { tag: "path", attrs: { d: "m8 22 4-11 4 11" } },
  ],
  humanTask: [
    { tag: "path", attrs: { d: "M2 21a8 8 0 0 1 13.292-6" } },
    { tag: "circle", attrs: { cx: "10", cy: "8", r: "5" } },
    { tag: "path", attrs: { d: "m16 19 2 2 4-4" } },
  ],
  fail: [
    { tag: "path", attrs: { d: "m15 9-6 6" } },
    {
      tag: "path",
      attrs: {
        d: "M2.586 16.726A2 2 0 0 1 2 15.312V8.688a2 2 0 0 1 .586-1.414l4.688-4.688A2 2 0 0 1 8.688 2h6.624a2 2 0 0 1 1.414.586l4.688 4.688A2 2 0 0 1 22 8.688v6.624a2 2 0 0 1-.586 1.414l-4.688 4.688a2 2 0 0 1-1.414.586H8.688a2 2 0 0 1-1.414-.586z",
      },
    },
    { tag: "path", attrs: { d: "m9 9 6 6" } },
  ],
  play: [
    {
      tag: "path",
      attrs: {
        d: "M5 5a2 2 0 0 1 3.008-1.728l11.997 6.998a2 2 0 0 1 .003 3.458l-12 7A2 2 0 0 1 5 19z",
      },
    },
  ],
  plus: [
    { tag: "path", attrs: { d: "M5 12h14" } },
    { tag: "path", attrs: { d: "M12 5v14" } },
  ],
  search: [
    { tag: "path", attrs: { d: "m21 21-4.34-4.34" } },
    { tag: "circle", attrs: { cx: "11", cy: "11", r: "8" } },
  ],
  chevron: [{ tag: "path", attrs: { d: "m9 18 6-6-6-6" } }],
  undo: [
    { tag: "path", attrs: { d: "M9 14 4 9l5-5" } },
    {
      tag: "path",
      attrs: { d: "M4 9h10.5a5.5 5.5 0 0 1 5.5 5.5a5.5 5.5 0 0 1-5.5 5.5H11" },
    },
  ],
  redo: [
    { tag: "path", attrs: { d: "m15 14 5-5-5-5" } },
    {
      tag: "path",
      attrs: { d: "M20 9H9.5A5.5 5.5 0 0 0 4 14.5A5.5 5.5 0 0 0 9.5 20H13" },
    },
  ],
  fit: [
    { tag: "path", attrs: { d: "M3 7V5a2 2 0 0 1 2-2h2" } },
    { tag: "path", attrs: { d: "M17 3h2a2 2 0 0 1 2 2v2" } },
    { tag: "path", attrs: { d: "M21 17v2a2 2 0 0 1-2 2h-2" } },
    { tag: "path", attrs: { d: "M7 21H5a2 2 0 0 1-2-2v-2" } },
  ],
  source: [
    { tag: "path", attrs: { d: "m18 16 4-4-4-4" } },
    { tag: "path", attrs: { d: "m6 8-4 4 4 4" } },
    { tag: "path", attrs: { d: "m14.5 4-5 16" } },
  ],
  check: [{ tag: "path", attrs: { d: "M20 6 9 17l-5-5" } }],
  download: [
    { tag: "path", attrs: { d: "M12 15V3" } },
    { tag: "path", attrs: { d: "M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4" } },
    { tag: "path", attrs: { d: "m7 10 5 5 5-5" } },
  ],
  upload: [
    { tag: "path", attrs: { d: "M12 3v12" } },
    { tag: "path", attrs: { d: "m17 8-5-5-5 5" } },
    { tag: "path", attrs: { d: "M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4" } },
  ],
  trash: [
    { tag: "path", attrs: { d: "M10 11v6" } },
    { tag: "path", attrs: { d: "M14 11v6" } },
    { tag: "path", attrs: { d: "M19 6v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6" } },
    { tag: "path", attrs: { d: "M3 6h18" } },
    { tag: "path", attrs: { d: "M8 6V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2" } },
  ],
  menu: [
    { tag: "path", attrs: { d: "M4 5h16" } },
    { tag: "path", attrs: { d: "M4 12h16" } },
    { tag: "path", attrs: { d: "M4 19h16" } },
  ],
  more: [
    { tag: "circle", attrs: { cx: "12", cy: "12", r: "1" } },
    { tag: "circle", attrs: { cx: "19", cy: "12", r: "1" } },
    { tag: "circle", attrs: { cx: "5", cy: "12", r: "1" } },
  ],
  close: [
    { tag: "path", attrs: { d: "M18 6 6 18" } },
    { tag: "path", attrs: { d: "m6 6 12 12" } },
  ],
  save: [
    {
      tag: "path",
      attrs: {
        d: "M15.2 3a2 2 0 0 1 1.4.6l3.8 3.8a2 2 0 0 1 .6 1.4V19a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2z",
      },
    },
    { tag: "path", attrs: { d: "M17 21v-7a1 1 0 0 0-1-1H8a1 1 0 0 0-1 1v7" } },
    { tag: "path", attrs: { d: "M7 3v4a1 1 0 0 0 1 1h7" } },
  ],
  lock: [
    {
      tag: "rect",
      attrs: { width: "18", height: "11", x: "3", y: "11", rx: "2", ry: "2" },
    },
    { tag: "path", attrs: { d: "M7 11V7a5 5 0 0 1 10 0v4" } },
  ],
  external: [
    { tag: "path", attrs: { d: "M15 3h6v6" } },
    { tag: "path", attrs: { d: "M10 14 21 3" } },
    {
      tag: "path",
      attrs: { d: "M18 13v6a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h6" },
    },
  ],
  copy: [
    {
      tag: "rect",
      attrs: { width: "14", height: "14", x: "8", y: "8", rx: "2", ry: "2" },
    },
    {
      tag: "path",
      attrs: { d: "M4 16c-1.1 0-2-.9-2-2V4c0-1.1.9-2 2-2h10c1.1 0 2 .9 2 2" },
    },
  ],
  refresh: [
    {
      tag: "path",
      attrs: { d: "M3 12a9 9 0 0 1 9-9 9.75 9.75 0 0 1 6.74 2.74L21 8" },
    },
    { tag: "path", attrs: { d: "M21 3v5h-5" } },
    {
      tag: "path",
      attrs: { d: "M21 12a9 9 0 0 1-9 9 9.75 9.75 0 0 1-6.74-2.74L3 16" },
    },
    { tag: "path", attrs: { d: "M8 16H3v5" } },
  ],
  warning: [
    {
      tag: "path",
      attrs: {
        d: "m21.73 18-8-14a2 2 0 0 0-3.48 0l-8 14A2 2 0 0 0 4 21h16a2 2 0 0 0 1.73-3",
      },
    },
    { tag: "path", attrs: { d: "M12 9v4" } },
    { tag: "path", attrs: { d: "M12 17h.01" } },
  ],
  help: [
    { tag: "circle", attrs: { cx: "12", cy: "12", r: "10" } },
    { tag: "path", attrs: { d: "M9.09 9a3 3 0 0 1 5.83 1c0 2-3 3-3 3" } },
    { tag: "path", attrs: { d: "M12 17h.01" } },
  ],
  logout: [
    { tag: "path", attrs: { d: "m16 17 5-5-5-5" } },
    { tag: "path", attrs: { d: "M21 12H9" } },
    { tag: "path", attrs: { d: "M9 21H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h4" } },
  ],
  cloud: [
    {
      tag: "path",
      attrs: { d: "M17.5 19H9a7 7 0 1 1 6.71-9h1.79a4.5 4.5 0 1 1 0 9Z" },
    },
  ],
  laptop: [
    {
      tag: "path",
      attrs: {
        d: "M18 5a2 2 0 0 1 2 2v8.526a2 2 0 0 0 .212.897l1.068 2.127a1 1 0 0 1-.9 1.45H3.62a1 1 0 0 1-.9-1.45l1.068-2.127A2 2 0 0 0 4 15.526V7a2 2 0 0 1 2-2z",
      },
    },
    { tag: "path", attrs: { d: "M20.054 15.987H3.946" } },
  ],
  panel: [
    {
      tag: "rect",
      attrs: { width: "18", height: "18", x: "3", y: "3", rx: "2" },
    },
    { tag: "path", attrs: { d: "M15 3v18" } },
  ],
  tidy: [
    {
      tag: "rect",
      attrs: { width: "7", height: "7", x: "3", y: "3", rx: "1" },
    },
    {
      tag: "rect",
      attrs: { width: "7", height: "7", x: "14", y: "3", rx: "1" },
    },
    {
      tag: "rect",
      attrs: { width: "7", height: "7", x: "14", y: "14", rx: "1" },
    },
    {
      tag: "rect",
      attrs: { width: "7", height: "7", x: "3", y: "14", rx: "1" },
    },
  ],
  failCircle: [
    { tag: "circle", attrs: { cx: "12", cy: "12", r: "10" } },
    { tag: "path", attrs: { d: "m15 9-6 6" } },
    { tag: "path", attrs: { d: "m9 9 6 6" } },
  ],
  manualTrigger: [
    { tag: "path", attrs: { d: "M14 4.1 12 6" } },
    { tag: "path", attrs: { d: "m5.1 8-2.9-.8" } },
    { tag: "path", attrs: { d: "m6 12-1.9 2" } },
    { tag: "path", attrs: { d: "M7.2 2.2 8 5.1" } },
    {
      tag: "path",
      attrs: {
        d: "M9.037 9.69a.498.498 0 0 1 .653-.653l11 4.5a.5.5 0 0 1-.074.949l-4.349 1.041a1 1 0 0 0-.74.739l-1.04 4.35a.5.5 0 0 1-.95.074z",
      },
    },
  ],
  webhook: [
    {
      tag: "path",
      attrs: {
        d: "M18 16.98h-5.99c-1.1 0-1.95.94-2.48 1.9A4 4 0 0 1 2 17c.01-.7.2-1.4.57-2",
      },
    },
    {
      tag: "path",
      attrs: { d: "m6 17 3.13-5.78c.53-.97.1-2.18-.5-3.1a4 4 0 1 1 6.89-4.06" },
    },
    {
      tag: "path",
      attrs: { d: "m12 6 3.13 5.73C15.66 12.7 16.9 13 18 13a4 4 0 0 1 0 8" },
    },
  ],
  schedule: [
    { tag: "path", attrs: { d: "M16 14v2.2l1.6 1" } },
    { tag: "path", attrs: { d: "M16 2v3" } },
    {
      tag: "path",
      attrs: {
        d: "M21 7.338V5a2 2 0 00-2-2H5a2 2 0 00-2 2v14a2 2 0 002 2h2.338",
      },
    },
    { tag: "path", attrs: { d: "M3 9h5.859" } },
    { tag: "path", attrs: { d: "M8 2v3" } },
    { tag: "circle", attrs: { cx: "16", cy: "16", r: "6" } },
  ],
  kafka: [
    { tag: "polyline", attrs: { points: "22 12 16 12 14 15 10 15 8 12 2 12" } },
    {
      tag: "path",
      attrs: {
        d: "M5.45 5.11 2 12v6a2 2 0 0 0 2 2h16a2 2 0 0 0 2-2v-6l-3.45-6.89A2 2 0 0 0 16.76 4H7.24a2 2 0 0 0-1.79 1.11z",
      },
    },
  ],
  appEvent: [
    {
      tag: "rect",
      attrs: { x: "2", y: "4", width: "20", height: "16", rx: "2" },
    },
    { tag: "path", attrs: { d: "M10 4v4" } },
    { tag: "path", attrs: { d: "M2 8h20" } },
    { tag: "path", attrs: { d: "M6 4v4" } },
  ],
  calledTrigger: [
    { tag: "path", attrs: { d: "M15 15 9 9" } },
    { tag: "path", attrs: { d: "M9 15h6V9" } },
    {
      tag: "rect",
      attrs: { x: "3", y: "3", width: "18", height: "18", rx: "2" },
    },
  ],
  agent: [
    { tag: "path", attrs: { d: "M12 8V4H8" } },
    {
      tag: "rect",
      attrs: { width: "16", height: "12", x: "4", y: "8", rx: "2" },
    },
    { tag: "path", attrs: { d: "M2 14h2" } },
    { tag: "path", attrs: { d: "M20 14h2" } },
    { tag: "path", attrs: { d: "M15 13v2" } },
    { tag: "path", attrs: { d: "M9 13v2" } },
  ],
  model: [
    {
      tag: "path",
      attrs: {
        d: "M12 5a3 3 0 1 0-5.997.125 4 4 0 0 0-2.526 5.77 4 4 0 0 0 .556 6.588A4 4 0 1 0 12 18Z",
      },
    },
    { tag: "path", attrs: { d: "M9 13a4.5 4.5 0 0 0 3-4" } },
    { tag: "path", attrs: { d: "M6.003 5.125A3 3 0 0 0 6.401 6.5" } },
    { tag: "path", attrs: { d: "M3.477 10.896a4 4 0 0 1 .585-.396" } },
    { tag: "path", attrs: { d: "M6 18a4 4 0 0 1-1.967-.516" } },
    { tag: "path", attrs: { d: "M12 13h4" } },
    { tag: "path", attrs: { d: "M12 18h6a2 2 0 0 1 2 2v1" } },
    { tag: "path", attrs: { d: "M12 8h8" } },
    { tag: "path", attrs: { d: "M16 8V5a2 2 0 0 1 2-2" } },
    { tag: "circle", attrs: { cx: "16", cy: "13", r: ".5" } },
    { tag: "circle", attrs: { cx: "18", cy: "3", r: ".5" } },
    { tag: "circle", attrs: { cx: "20", cy: "21", r: ".5" } },
    { tag: "circle", attrs: { cx: "20", cy: "8", r: ".5" } },
  ],
  tools: [
    {
      tag: "path",
      attrs: {
        d: "M14.7 6.3a1 1 0 0 0 0 1.4l1.6 1.6a1 1 0 0 0 1.4 0l3.106-3.105c.32-.322.863-.22.983.218a6 6 0 0 1-8.259 7.057l-7.91 7.91a1 1 0 0 1-2.999-3l7.91-7.91a6 6 0 0 1 7.057-8.259c.438.12.54.662.219.984z",
      },
    },
  ],
  memory: [
    { tag: "ellipse", attrs: { cx: "12", cy: "5", rx: "9", ry: "3" } },
    { tag: "path", attrs: { d: "M3 5V19A9 3 0 0 0 21 19V5" } },
    { tag: "path", attrs: { d: "M3 12A9 3 0 0 0 21 12" } },
  ],
  output: [
    {
      tag: "path",
      attrs: {
        d: "M4.226 20.925A2 2 0 0 0 6 22h12a2 2 0 0 0 2-2V8a2.4 2.4 0 0 0-.706-1.706l-3.588-3.588A2.4 2.4 0 0 0 14 2H6a2 2 0 0 0-2 2v3.127",
      },
    },
    { tag: "path", attrs: { d: "M14 2v5a1 1 0 0 0 1 1h5" } },
    { tag: "path", attrs: { d: "m5 11-3 3" } },
    { tag: "path", attrs: { d: "m5 17-3-3h10" } },
  ],
  forEach: [
    { tag: "path", attrs: { d: "M4 10a8 8 0 1 1 8 8H4" } },
    { tag: "path", attrs: { d: "m8 22-4-4 4-4" } },
  ],
  callWorkflow: [
    {
      tag: "path",
      attrs: { d: "M4 10c-1.1 0-2-.9-2-2V4c0-1.1.9-2 2-2h4c1.1 0 2 .9 2 2" },
    },
    {
      tag: "path",
      attrs: { d: "M10 16c-1.1 0-2-.9-2-2v-4c0-1.1.9-2 2-2h4c1.1 0 2 .9 2 2" },
    },
    {
      tag: "rect",
      attrs: { width: "8", height: "8", x: "14", y: "14", rx: "2" },
    },
  ],
  textTemplate: [
    { tag: "path", attrs: { d: "M12 20h-1a2 2 0 0 1-2-2 2 2 0 0 1-2 2H6" } },
    { tag: "path", attrs: { d: "M13 8h7a2 2 0 0 1 2 2v4a2 2 0 0 1-2 2h-7" } },
    { tag: "path", attrs: { d: "M5 16H4a2 2 0 0 1-2-2v-4a2 2 0 0 1 2-2h1" } },
    { tag: "path", attrs: { d: "M6 4h1a2 2 0 0 1 2 2 2 2 0 0 1 2-2h1" } },
    { tag: "path", attrs: { d: "M9 6v12" } },
  ],
  execute: [
    {
      tag: "path",
      attrs: {
        d: "M14 2v6a2 2 0 0 0 .245.96l5.51 10.08A2 2 0 0 1 18 22H6a2 2 0 0 1-1.755-2.96l5.51-10.08A2 2 0 0 0 10 8V2",
      },
    },
    { tag: "path", attrs: { d: "M6.453 15h11.094" } },
    { tag: "path", attrs: { d: "M8.5 2h7" } },
  ],
  pin: [
    { tag: "path", attrs: { d: "M12 17v5" } },
    {
      tag: "path",
      attrs: {
        d: "M9 10.76a2 2 0 0 1-1.11 1.79l-1.78.9A2 2 0 0 0 5 15.24V16a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1v-.76a2 2 0 0 0-1.11-1.79l-1.78-.9A2 2 0 0 1 15 10.76V7a1 1 0 0 1 1-1 2 2 0 0 0 0-4H8a2 2 0 0 0 0 4 1 1 0 0 1 1 1z",
      },
    },
  ],
  unpin: [
    { tag: "path", attrs: { d: "M12 17v5" } },
    {
      tag: "path",
      attrs: { d: "M15 9.34V7a1 1 0 0 1 1-1 2 2 0 0 0 0-4H7.89" },
    },
    { tag: "path", attrs: { d: "m2 2 20 20" } },
    {
      tag: "path",
      attrs: {
        d: "M9 9v1.76a2 2 0 0 1-1.11 1.79l-1.78.9A2 2 0 0 0 5 15.24V16a1 1 0 0 0 1 1h11",
      },
    },
  ],
  stale: [
    { tag: "path", attrs: { d: "M12 6v6l4 2" } },
    { tag: "path", attrs: { d: "M20 12v5" } },
    { tag: "path", attrs: { d: "M20 21h.01" } },
    { tag: "path", attrs: { d: "M21.25 8.2A10 10 0 1 0 16 21.16" } },
  ],
  breakpoint: [
    { tag: "circle", attrs: { cx: "12", cy: "12", r: "1" } },
    { tag: "circle", attrs: { cx: "12", cy: "12", r: "10" } },
  ],
  runHistory: [
    {
      tag: "path",
      attrs: { d: "M3 12a9 9 0 1 0 9-9 9.75 9.75 0 0 0-6.74 2.74L3 8" },
    },
    { tag: "path", attrs: { d: "M3 3v5h5" } },
    { tag: "path", attrs: { d: "M12 7v5l4 2" } },
  ],
  stickyNote: [
    {
      tag: "path",
      attrs: {
        d: "M21 9a2.4 2.4 0 0 0-.706-1.706l-3.588-3.588A2.4 2.4 0 0 0 15 3H5a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2z",
      },
    },
    { tag: "path", attrs: { d: "M15 3v5a1 1 0 0 0 1 1h5" } },
  ],
  minimap: [
    {
      tag: "path",
      attrs: {
        d: "M14.106 5.553a2 2 0 0 0 1.788 0l3.659-1.83A1 1 0 0 1 21 4.619v12.764a1 1 0 0 1-.553.894l-4.553 2.277a2 2 0 0 1-1.788 0l-4.212-2.106a2 2 0 0 0-1.788 0l-3.659 1.83A1 1 0 0 1 3 19.381V6.618a1 1 0 0 1 .553-.894l4.553-2.277a2 2 0 0 1 1.788 0z",
      },
    },
    { tag: "path", attrs: { d: "M15 5.764v15" } },
    { tag: "path", attrs: { d: "M9 3.236v15" } },
  ],
  zoomIn: [
    { tag: "circle", attrs: { cx: "11", cy: "11", r: "8" } },
    { tag: "line", attrs: { x1: "21", x2: "16.65", y1: "21", y2: "16.65" } },
    { tag: "line", attrs: { x1: "11", x2: "11", y1: "8", y2: "14" } },
    { tag: "line", attrs: { x1: "8", x2: "14", y1: "11", y2: "11" } },
  ],
  zoomOut: [
    { tag: "circle", attrs: { cx: "11", cy: "11", r: "8" } },
    { tag: "line", attrs: { x1: "21", x2: "16.65", y1: "21", y2: "16.65" } },
    { tag: "line", attrs: { x1: "8", x2: "14", y1: "11", y2: "11" } },
  ],
  drag: [
    { tag: "circle", attrs: { cx: "9", cy: "12", r: "1" } },
    { tag: "circle", attrs: { cx: "9", cy: "5", r: "1" } },
    { tag: "circle", attrs: { cx: "9", cy: "19", r: "1" } },
    { tag: "circle", attrs: { cx: "15", cy: "12", r: "1" } },
    { tag: "circle", attrs: { cx: "15", cy: "5", r: "1" } },
    { tag: "circle", attrs: { cx: "15", cy: "19", r: "1" } },
  ],
  spinner: [{ tag: "path", attrs: { d: "M21 12a9 9 0 1 1-6.219-8.56" } }],
  edit: [
    {
      tag: "path",
      attrs: {
        d: "M21.174 6.812a1 1 0 0 0-3.986-3.987L3.842 16.174a2 2 0 0 0-.5.83l-1.321 4.352a.5.5 0 0 0 .623.622l4.353-1.32a2 2 0 0 0 .83-.497z",
      },
    },
    { tag: "path", attrs: { d: "m15 5 4 4" } },
  ],
  docs: [
    { tag: "path", attrs: { d: "M12 5v16" } },
    {
      tag: "path",
      attrs: {
        d: "M20.001 19A2 2 0 0022 17V5a2 2 0 00-1.999-2L16 3.002A5 5 0 0012 5a5 5 0 00-4-2H4a2 2 0 00-2 2v12a2 2 0 001.999 2H8a5 5 0 014 2 5 5 0 014-2z",
      },
    },
  ],
  expand: [
    { tag: "path", attrs: { d: "M15 3h6v6" } },
    { tag: "path", attrs: { d: "m21 3-7 7" } },
    { tag: "path", attrs: { d: "m3 21 7-7" } },
    { tag: "path", attrs: { d: "M9 21H3v-6" } },
  ],
  chevronLeft: [{ tag: "path", attrs: { d: "m15 18-6-6 6-6" } }],
  chevronDown: [{ tag: "path", attrs: { d: "m6 9 6 6 6-6" } }],
  schemaView: [
    { tag: "path", attrs: { d: "M8 5h13" } },
    { tag: "path", attrs: { d: "M13 12h8" } },
    { tag: "path", attrs: { d: "M13 19h8" } },
    { tag: "path", attrs: { d: "M3 10a2 2 0 0 0 2 2h3" } },
    { tag: "path", attrs: { d: "M3 5v12a2 2 0 0 0 2 2h3" } },
  ],
  tableView: [
    { tag: "path", attrs: { d: "M3 9h18" } },
    { tag: "path", attrs: { d: "M9 3v18" } },
    {
      tag: "rect",
      attrs: { x: "3", y: "3", width: "18", height: "18", rx: "2" },
    },
  ],
  jsonView: [
    {
      tag: "path",
      attrs: {
        d: "M6 22a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h8a2.4 2.4 0 0 1 1.704.706l3.588 3.588A2.4 2.4 0 0 1 20 8v12a2 2 0 0 1-2 2z",
      },
    },
    { tag: "path", attrs: { d: "M14 2v5a1 1 0 0 0 1 1h5" } },
    {
      tag: "path",
      attrs: {
        d: "M10 12a1 1 0 0 0-1 1v1a1 1 0 0 1-1 1 1 1 0 0 1 1 1v1a1 1 0 0 0 1 1",
      },
    },
    {
      tag: "path",
      attrs: {
        d: "M14 18a1 1 0 0 0 1-1v-1a1 1 0 0 1 1-1 1 1 0 0 1-1-1v-1a1 1 0 0 0-1-1",
      },
    },
  ],
  typeText: [
    { tag: "path", attrs: { d: "M12 4v16" } },
    { tag: "path", attrs: { d: "M4 7V5a1 1 0 0 1 1-1h14a1 1 0 0 1 1 1v2" } },
    { tag: "path", attrs: { d: "M9 20h6" } },
  ],
  typeNumber: [
    { tag: "line", attrs: { x1: "4", x2: "20", y1: "9", y2: "9" } },
    { tag: "line", attrs: { x1: "4", x2: "20", y1: "15", y2: "15" } },
    { tag: "line", attrs: { x1: "10", x2: "8", y1: "3", y2: "21" } },
    { tag: "line", attrs: { x1: "16", x2: "14", y1: "3", y2: "21" } },
  ],
  typeBoolean: [
    { tag: "circle", attrs: { cx: "9", cy: "12", r: "3" } },
    {
      tag: "rect",
      attrs: { width: "20", height: "14", x: "2", y: "5", rx: "7" },
    },
  ],
  typeList: [
    { tag: "path", attrs: { d: "M3 5h.01" } },
    { tag: "path", attrs: { d: "M3 12h.01" } },
    { tag: "path", attrs: { d: "M3 19h.01" } },
    { tag: "path", attrs: { d: "M8 5h13" } },
    { tag: "path", attrs: { d: "M8 12h13" } },
    { tag: "path", attrs: { d: "M8 19h13" } },
  ],
  typeObject: [
    {
      tag: "path",
      attrs: {
        d: "M21 8a2 2 0 0 0-1-1.73l-7-4a2 2 0 0 0-2 0l-7 4A2 2 0 0 0 3 8v8a2 2 0 0 0 1 1.73l7 4a2 2 0 0 0 2 0l7-4A2 2 0 0 0 21 16Z",
      },
    },
    { tag: "path", attrs: { d: "m3.3 7 8.7 5 8.7-5" } },
    { tag: "path", attrs: { d: "M12 22V12" } },
  ],
  typeDate: [
    { tag: "path", attrs: { d: "M8 2v3" } },
    { tag: "path", attrs: { d: "M16 2v3" } },
    {
      tag: "rect",
      attrs: { x: "3", y: "3", width: "18", height: "18", rx: "2" },
    },
    { tag: "path", attrs: { d: "M3 9h18" } },
  ],
  typeFile: [
    {
      tag: "path",
      attrs: {
        d: "M6 22a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h8a2.4 2.4 0 0 1 1.704.706l3.588 3.588A2.4 2.4 0 0 1 20 8v12a2 2 0 0 1-2 2z",
      },
    },
    { tag: "path", attrs: { d: "M14 2v5a1 1 0 0 0 1 1h5" } },
  ],
  typeAny: [
    { tag: "path", attrs: { d: "M10.1 2.182a10 10 0 0 1 3.8 0" } },
    { tag: "path", attrs: { d: "M13.9 21.818a10 10 0 0 1-3.8 0" } },
    { tag: "path", attrs: { d: "M17.609 3.721a10 10 0 0 1 2.69 2.7" } },
    { tag: "path", attrs: { d: "M2.182 13.9a10 10 0 0 1 0-3.8" } },
    { tag: "path", attrs: { d: "M20.279 17.609a10 10 0 0 1-2.7 2.69" } },
    { tag: "path", attrs: { d: "M21.818 10.1a10 10 0 0 1 0 3.8" } },
    { tag: "path", attrs: { d: "M3.721 6.391a10 10 0 0 1 2.7-2.69" } },
    { tag: "path", attrs: { d: "M6.391 20.279a10 10 0 0 1-2.69-2.7" } },
  ],
  overview: [
    { tag: "path", attrs: { d: "m12 14 4-4" } },
    { tag: "path", attrs: { d: "M3.34 19a10 10 0 1 1 17.32 0" } },
  ],
  clusters: [
    {
      tag: "rect",
      attrs: { width: "20", height: "8", x: "2", y: "2", rx: "2", ry: "2" },
    },
    {
      tag: "rect",
      attrs: { width: "20", height: "8", x: "2", y: "14", rx: "2", ry: "2" },
    },
    { tag: "line", attrs: { x1: "6", x2: "6.01", y1: "6", y2: "6" } },
    { tag: "line", attrs: { x1: "6", x2: "6.01", y1: "18", y2: "18" } },
  ],
  metrics: [
    { tag: "path", attrs: { d: "M3 3v16a2 2 0 0 0 2 2h16" } },
    { tag: "path", attrs: { d: "m19 9-5 5-4-4-3 3" } },
  ],
  logs: [
    { tag: "path", attrs: { d: "M15 12h-5" } },
    { tag: "path", attrs: { d: "M15 8h-5" } },
    { tag: "path", attrs: { d: "M19 17V5a2 2 0 0 0-2-2H4" } },
    {
      tag: "path",
      attrs: {
        d: "M8 21h12a2 2 0 0 0 2-2v-1a1 1 0 0 0-1-1H11a1 1 0 0 0-1 1v1a2 2 0 1 1-4 0V5a2 2 0 1 0-4 0v2a1 1 0 0 0 1 1h3",
      },
    },
  ],
  alerts: [
    { tag: "path", attrs: { d: "M10.268 21a2 2 0 0 0 3.464 0" } },
    {
      tag: "path",
      attrs: {
        d: "M3.262 15.326A1 1 0 0 0 4 17h16a1 1 0 0 0 .74-1.673C19.41 13.956 18 12.499 18 8A6 6 0 0 0 6 8c0 4.499-1.411 5.956-2.738 7.326",
      },
    },
  ],
  alertFiring: [
    { tag: "path", attrs: { d: "M10.268 21a2 2 0 0 0 3.464 0" } },
    { tag: "path", attrs: { d: "M22 8c0-2.3-.8-4.3-2-6" } },
    {
      tag: "path",
      attrs: {
        d: "M3.262 15.326A1 1 0 0 0 4 17h16a1 1 0 0 0 .74-1.673C19.41 13.956 18 12.499 18 8A6 6 0 0 0 6 8c0 4.499-1.411 5.956-2.738 7.326",
      },
    },
    { tag: "path", attrs: { d: "M4 2C2.8 3.7 2 5.7 2 8" } },
  ],
  incidents: [
    { tag: "path", attrs: { d: "M7 18v-6a5 5 0 1 1 10 0v6" } },
    {
      tag: "path",
      attrs: {
        d: "M5 21a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1v-1a2 2 0 0 0-2-2H7a2 2 0 0 0-2 2z",
      },
    },
    { tag: "path", attrs: { d: "M21 12h1" } },
    { tag: "path", attrs: { d: "M18.5 4.5 18 5" } },
    { tag: "path", attrs: { d: "M2 12h1" } },
    { tag: "path", attrs: { d: "M12 2v1" } },
    { tag: "path", attrs: { d: "m4.929 4.929.707.707" } },
    { tag: "path", attrs: { d: "M12 12v6" } },
  ],
  approvals: [
    {
      tag: "path",
      attrs: { d: "M14 13V8.5C14 7 15 7 15 5a3 3 0 0 0-6 0c0 2 1 2 1 3.5V13" },
    },
    {
      tag: "path",
      attrs: {
        d: "M20 15.5a2.5 2.5 0 0 0-2.5-2.5h-11A2.5 2.5 0 0 0 4 15.5V17a1 1 0 0 0 1 1h14a1 1 0 0 0 1-1z",
      },
    },
    { tag: "path", attrs: { d: "M5 22h14" } },
  ],
  compose: [
    {
      tag: "path",
      attrs: {
        d: "M22 7.7c0-.6-.4-1.2-.8-1.5l-6.3-3.9a1.72 1.72 0 0 0-1.7 0l-10.3 6c-.5.2-.9.8-.9 1.4v6.6c0 .5.4 1.2.8 1.5l6.3 3.9a1.72 1.72 0 0 0 1.7 0l10.3-6c.5-.3.9-1 .9-1.5Z",
      },
    },
    { tag: "path", attrs: { d: "M10 21.9V14L2.1 9.1" } },
    { tag: "path", attrs: { d: "m10 14 11.9-6.9" } },
    { tag: "path", attrs: { d: "M14 19.8v-8.1" } },
    { tag: "path", attrs: { d: "M18 17.5V9.4" } },
  ],
  kubernetes: [
    { tag: "circle", attrs: { cx: "12", cy: "12", r: "8" } },
    { tag: "path", attrs: { d: "M12 2v7.5" } },
    { tag: "path", attrs: { d: "m19 5-5.23 5.23" } },
    { tag: "path", attrs: { d: "M22 12h-7.5" } },
    { tag: "path", attrs: { d: "m19 19-5.23-5.23" } },
    { tag: "path", attrs: { d: "M12 14.5V22" } },
    { tag: "path", attrs: { d: "M10.23 13.77 5 19" } },
    { tag: "path", attrs: { d: "M9.5 12H2" } },
    { tag: "path", attrs: { d: "M10.23 10.23 5 5" } },
    { tag: "circle", attrs: { cx: "12", cy: "12", r: "2.5" } },
  ],
  drain: [
    { tag: "circle", attrs: { cx: "12", cy: "12", r: "10" } },
    { tag: "line", attrs: { x1: "10", x2: "10", y1: "15", y2: "9" } },
    { tag: "line", attrs: { x1: "14", x2: "14", y1: "15", y2: "9" } },
  ],
  revoke: [
    { tag: "circle", attrs: { cx: "12", cy: "12", r: "10" } },
    { tag: "path", attrs: { d: "M4.929 4.929 19.07 19.071" } },
  ],
  critical: [
    { tag: "path", attrs: { d: "M12 16h.01" } },
    { tag: "path", attrs: { d: "M12 8v4" } },
    {
      tag: "path",
      attrs: {
        d: "M15.312 2a2 2 0 0 1 1.414.586l4.688 4.688A2 2 0 0 1 22 8.688v6.624a2 2 0 0 1-.586 1.414l-4.688 4.688a2 2 0 0 1-1.414.586H8.688a2 2 0 0 1-1.414-.586l-4.688-4.688A2 2 0 0 1 2 15.312V8.688a2 2 0 0 1 .586-1.414l4.688-4.688A2 2 0 0 1 8.688 2z",
      },
    },
  ],
  info: [
    { tag: "circle", attrs: { cx: "12", cy: "12", r: "10" } },
    { tag: "path", attrs: { d: "M12 16v-4" } },
    { tag: "path", attrs: { d: "M12 8h.01" } },
  ],
  degraded: [
    { tag: "circle", attrs: { cx: "12", cy: "12", r: "10" } },
    { tag: "line", attrs: { x1: "12", x2: "12", y1: "8", y2: "12" } },
    { tag: "line", attrs: { x1: "12", x2: "12.01", y1: "16", y2: "16" } },
  ],
  ok: [
    { tag: "circle", attrs: { cx: "12", cy: "12", r: "10" } },
    { tag: "path", attrs: { d: "m16 9-5.5 5.5L8 12" } },
  ],
  off: [
    { tag: "path", attrs: { d: "m2 2 20 20" } },
    { tag: "path", attrs: { d: "M8.35 2.69A10 10 0 0 1 21.3 15.65" } },
    { tag: "path", attrs: { d: "M19.08 19.08A10 10 0 1 1 4.92 4.92" } },
  ],
};
