# Copyright 2026 Firefly Software Foundation.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# Author: Firefly Software Foundation
# SPDX-License-Identifier: Apache-2.0
"""Inventory first-party source attribution without importing or modifying product files.

Exact-path exceptions preserve commentless and generated bytes. Unknown formats,
stale exceptions, external symlinks, and missing module documentation stay visible.
"""

from __future__ import annotations

import argparse
import ast
import hashlib
import json
import os
import re
import stat
import tokenize
import tomllib
from pathlib import Path
from typing import Any

PRUNED = {
    ".git",
    ".local",
    ".superpowers",
    ".venv",
    "venv",
    ".tox",
    "node_modules",
    "__pycache__",
    ".hypothesis",
    ".pytest_cache",
    ".mypy_cache",
    ".ruff_cache",
    "build",
    "dist",
    ".cache",
    ".angular",
    "test-results",
    "playwright-report",
}
HASH_SUFFIXES = {".py", ".sh", ".bash", ".zsh", ".yaml", ".yml", ".toml", ".ini", ".cfg", ".Dockerfile"}
HASH_NAMES = {"Dockerfile", "Makefile", ".gitignore", ".dockerignore"}
XML_SUFFIXES = {".svg", ".md", ".html", ".xml", ".plist"}
LEGAL_NAMES = {"LICENSE", "NOTICE"}
BOILERPLATE = (
    'Licensed under the Apache License, Version 2.0 (the "License");',
    "you may not use this file except in compliance with the License.",
    "You may obtain a copy of the License at",
    "http://www.apache.org/licenses/LICENSE-2.0",
    "Unless required by applicable law or agreed to in writing, software",
    'distributed under the License is distributed on an "AS IS" BASIS,',
    "WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.",
    "See the License for the specific language governing permissions and",
    "limitations under the License.",
    "Author: Firefly Software Foundation",
    "SPDX-License-Identifier: Apache-2.0",
)


def exclusion(name: str) -> str | None:
    """Prune only named nonpublication trees and private/cache file families."""
    if name in PRUNED or name.endswith(".egg-info"):
        return "dependency, private evidence, or generated build/cache"
    if name == ".env" or name.startswith(".env.") or name.endswith((".pyc", ".pyo", ".pem", ".key")):
        return "private credentials or interpreter cache"
    if name == ".DS_Store":
        return "operating-system metadata"
    return None


def inventory(root: Path) -> tuple[list[Path], list[dict[str, str]]]:
    """Do not descend into ignored directories or follow directory symlinks."""
    files: list[Path] = []
    excluded: list[dict[str, str]] = []

    def traversal_error(error: OSError) -> None:
        raise error

    for current, dirs, names in os.walk(root, followlinks=False, onerror=traversal_error):
        base = Path(current)
        for name in sorted(dirs + names):
            path = base / name
            reason = exclusion(name)
            if path.relative_to(root).as_posix() in {
                "desktop/work",
                "desktop/src-tauri/target",
                "desktop/src-tauri/gen",
                "desktop/src-tauri/binaries",
            }:
                reason = "generated desktop build output or frozen sidecar"
            if path.parent == root and name in LEGAL_NAMES:
                reason = "project legal text; not a source header target"
            if reason:
                excluded.append({"path": path.relative_to(root).as_posix(), "reason": reason})
                if name in dirs:
                    dirs.remove(name)
            elif path.is_symlink() or name in names:
                files.append(path)
                if name in dirs:
                    dirs.remove(name)
        dirs.sort()
    return sorted(files), sorted(excluded, key=lambda item: item["path"])


def safe_path(value: object) -> str:
    """Exception paths are literal portable relative paths, never globs."""
    if not isinstance(value, str) or not value or any(c in value for c in "*?[]\\"):
        raise ValueError("Exception paths must be nonempty literal relative paths")
    path = Path(value)
    if path.is_absolute() or ".." in path.parts or path.as_posix() != value or value == ".":
        raise ValueError("Exception paths must be normalized and inside the inventory root")
    return value


def load_exceptions(path: Path, *, required: bool = False) -> dict[str, dict[str, Any]]:
    """Reject configuration aliases before reading; only an absent default is optional."""
    absolute = path.absolute()
    component = Path(absolute.anchor)
    for part in absolute.parts[1:]:
        component = component / part
        try:
            mode = component.lstat().st_mode
        except FileNotFoundError:
            if required:
                raise
            return {}
        if stat.S_ISLNK(mode):
            raise ValueError("The inventory configuration and its ancestors must not be symlinks")
    data = tomllib.loads(path.read_text(encoding="utf-8"))
    if data.get("version") != 1 or set(data) - {"version", "exceptions"}:
        raise ValueError("Expected inventory version 1 and only version/exceptions fields")
    result = {}
    entries = data.get("exceptions", [])
    if not isinstance(entries, list):
        raise ValueError("Exceptions must be an array of tables")
    for entry in entries:
        if not isinstance(entry, dict):
            raise ValueError("Each exception must be a table")
        name = safe_path(entry.get("path"))
        if name in result:
            raise ValueError(f"Duplicate exception: {name}")
        result[name] = entry
    return result


def leading_comment(path: Path, text: str) -> str | None:
    """Only comments before executable content qualify as the attribution header."""
    suffix = path.with_suffix("").suffix if path.suffix == ".tmpl" else path.suffix
    if suffix in {".css", ".scss", ".ts", ".js", ".mjs", ".rs"}:
        value = text.lstrip()
        if value.startswith("/*") and "*/" in value:
            return "\n".join(
                line.strip().removeprefix("*").strip() for line in value[2 : value.index("*/")].splitlines()
            )
        return ""
    if suffix in XML_SUFFIXES:
        value = re.sub(r"^\s*<\?xml[^>]*\?>", "", text, count=1).lstrip()
        if value.startswith("<!--") and "-->" in value:
            return "\n".join(line.strip() for line in value[4 : value.index("-->")].splitlines())
        return ""
    prefix = "--" if suffix == ".sql" else "#"
    if suffix not in HASH_SUFFIXES | {".sql"} and path.name not in HASH_NAMES:
        return None
    lines = []
    for index, line in enumerate(text.splitlines()):
        if index == 0 and line.startswith("#!"):
            continue
        stripped = line.strip()
        if not stripped:
            continue
        if not stripped.startswith(prefix):
            break
        lines.append(stripped.removeprefix(prefix).strip())
    return "\n".join(lines)


def inspect(root: Path, exceptions: dict[str, dict[str, Any]]) -> dict[str, Any]:
    """Return deterministic actionable facts; quality of prose still needs review."""
    files, excluded = inventory(root)
    issues: list[dict[str, str]] = []
    entries = []

    def issue(path: str, code: str, message: str) -> None:
        issues.append({"path": path, "code": code, "message": message})

    seen = {path.relative_to(root).as_posix() for path in files}
    for name in sorted(exceptions.keys() - seen):
        issue(name, "stale-exception", "Remove the stale/excluded entry or restore its intended source file.")
    for path in files:
        name = path.relative_to(root).as_posix()
        exception = exceptions.get(name)
        if path.is_symlink():
            # Even internal aliases need deliberate review; never inspect the linked bytes.
            issue(name, "symlink", "Replace with source or review the alias separately; symlinks are not scanned.")
            entries.append({"path": name, "coverage": "symlink"})
            continue
        if exception:
            kind = exception.get("kind")
            required = {"reason", "copyright", "license"}
            if kind != "third-party":
                required.add("author")
            if kind in {"generated", "third-party"}:
                required.add("source")
            if kind == "immutable-fixture":
                required.add("sha256")
            if kind not in {"commentless", "generated", "third-party", "immutable-fixture"} or any(
                not isinstance(exception.get(key), str) or not exception[key].strip() for key in required
            ):
                issue(name, "invalid-exception", "Supply kind, reason, ownership/license and required provenance.")
            elif kind != "third-party" and (
                exception["license"] != "Apache-2.0"
                or exception["author"] != "Firefly Software Foundation"
                or not re.fullmatch(r"Copyright .+ Firefly Software Foundation\.", exception["copyright"])
            ):
                issue(name, "invalid-exception", "First-party inventory requires Foundation ownership and Apache-2.0.")
            if kind == "generated" and exception.get("source"):
                try:
                    source = safe_path(exception["source"])
                    if source not in seen or (root / source).is_symlink() or source == name:
                        raise ValueError
                except ValueError:
                    issue(name, "missing-generator", "Point source to the inventoried local generator or source file.")
            if kind == "commentless" and leading_comment(path, "") is not None:
                issue(
                    name,
                    "invalid-exception",
                    "Comment-capable source needs a header; use generated only with provenance.",
                )
            if kind == "immutable-fixture":
                digest = exception.get("sha256", "")
                if not name.startswith("tests/fixtures/") or not re.fullmatch(r"[0-9a-f]{64}", digest):
                    issue(name, "invalid-exception", "Immutable fixtures need an exact test fixture path and SHA-256.")
                elif hashlib.sha256(path.read_bytes()).hexdigest() != digest:
                    issue(name, "fixture-drift", "Fixture bytes changed; review source-position and hash contracts.")
            entries.append({"path": name, "coverage": str(kind)})
            continue
        try:
            if path.suffix == ".py":
                with tokenize.open(path) as source_file:
                    text = source_file.read()
            else:
                text = path.read_text(encoding="utf-8")
        except (OSError, UnicodeError, SyntaxError):
            issue(name, "unreadable-source", "Provide a valid source encoding or declare the binary/format ownership.")
            entries.append({"path": name, "coverage": "unreadable"})
            continue
        header = leading_comment(path, text)
        entries.append({"path": name, "coverage": "header" if header is not None else "uncovered"})
        if header is None:
            issue(name, "uncovered-format", "Declare an exact-path commentless/generated/third-party exception.")
        elif not all(line in header.splitlines() for line in BOILERPLATE) or not re.search(
            r"(?m)^\s*Copyright [0-9][0-9, –-]* Firefly Software Foundation\.\s*$", header
        ):
            issue(
                name, "missing-header", "Add the full Apache-2.0 comment header, Foundation copyright, Author and SPDX."
            )
        suffix = path.with_suffix("").suffix if path.suffix == ".tmpl" else path.suffix
        if suffix == ".py":
            try:
                module = ast.parse(text, filename=name)
            except SyntaxError:
                issue(name, "python-syntax", "Fix invalid Python before checking module documentation.")
            else:
                if not (ast.get_docstring(module) or "").strip():
                    issue(name, "missing-docstring", "Add a meaningful module responsibility docstring before imports.")
    issues.sort(key=lambda item: (item["path"], item["code"]))
    return {
        "version": 1,
        "files": entries,
        "excluded": excluded,
        "issues": issues,
        "summary": {"files": len(entries), "excluded": len(excluded), "issues": len(issues)},
    }


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", type=Path, default=Path(__file__).resolve().parents[1])
    parser.add_argument(
        "--inventory", type=Path, help="Exact-path TOML inventory (default: docs/contributing/source-inventory.toml)"
    )
    parser.add_argument("--strict", action="store_true", help="Exit 1 if any coverage issue remains")
    parser.add_argument("--format", choices=("text", "json"), default="text")
    args = parser.parse_args()
    try:
        root = args.root.resolve(strict=True)
        if not root.is_dir():
            raise ValueError("Inventory root must be a directory")
        config = args.inventory or root / "docs/contributing/source-inventory.toml"
        report = inspect(root, load_exceptions(config, required=args.inventory is not None))
    except (OSError, ValueError) as error:
        # Do not print file contents: config may have been pointed at the wrong file.
        report = {
            "error": type(error).__name__,
            "message": "Invalid root/inventory configuration or unreadable source directory.",
        }
        print(json.dumps(report, sort_keys=True) if args.format == "json" else report["message"])
        return 2
    if args.format == "json":
        print(json.dumps(report, indent=2, sort_keys=True))
    else:
        for item in report["issues"]:
            print(f"{item['path']}: {item['code']}: {item['message']}")
        summary = report["summary"]
        print(f"{summary['files']} files; {summary['excluded']} excluded entries; {summary['issues']} issues")
    return 1 if args.strict and report["issues"] else 0


if __name__ == "__main__":
    raise SystemExit(main())
