# Copyright 2026 Firefly Software Foundation.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# Author: Firefly Software Foundation
# SPDX-License-Identifier: Apache-2.0

"""The editor's /studio/local/* bodies accept the documented examples and refuse ambiguous targets."""

import json
import re
from pathlib import Path

import pytest
from pydantic import ValidationError

from firefly_weave.studio import local_contracts as lc

# The shared instance-key cases, generated by scripts/language_fixtures.py from firefly_weave.contracts.instance_keys.
SHARED_KEYS = json.loads(
    (Path(__file__).resolve().parents[2] / "studio/tests/fixtures/language/instance-keys.json").read_text("utf-8")
)
# Step IDs are ResourceName values, so the synthetic engine nodes (@join:..., @branch:...) are not targets.
STEP_KEYS = [case for case in SHARED_KEYS["valid"] if not case["node_id"].startswith("@")]

EXECUTE_REQUEST = {
    "source": "<yaml or json>",
    "format": "yaml",
    "definitions": [{"apiVersion": "weave/v1alpha1", "kind": "Action", "...": "..."}],
    "workflows": {
        "notify-customer@1.0.0": {
            "source": "<yaml>",
            "format": "yaml",
            "mocks": {"node:send-mail": {"id": "m-9"}},
        }
    },
    "catalog": "project",
    "refreshCatalog": False,
    "stubUnresolved": True,
    "input": {"amount": 1500, "orders": [{"id": "o-1"}, {"id": "o-2"}]},
    "mocks": {"node:check": {"eligible": True}, "node:send[1]": {"id": "m-1"}},
    "scripts": {
        "signals": {"wait-paid": {"payload": {"paid": True}}},
        "humans": {"approval": {"decision": "approve", "data": {}}},
        "aiTurns": {"support": {"turns": [{"result": {"text": "Shipped."}}]}},
        "autoAdvanceWaits": True,
    },
    "target": {"mode": "step", "stepId": "send", "instanceKey": "send[1]"},
    "now": "2026-10-07T10:00:00Z",
}
EXECUTE_RESPONSE = {
    "status": "blocked",
    "compile": {
        "ok": True,
        "sliced": True,
        "artifactDigest": "0" * 64,
        "diagnostics": [],
        "stubs": ["crm.lookup@1.0.0"],
    },
    "trace": [
        {
            "index": 0,
            "nodeId": "check",
            "instanceKey": "",
            "kind": "action",
            "status": "completed",
            "input": {"id": "c-1"},
            "output": {"eligible": True},
            "virtualTime": "2026-10-07T10:00:00Z",
        },
        {
            "index": 1,
            "nodeId": "send",
            "instanceKey": "send[0]",
            "kind": "action",
            "status": "completed",
            "output": {"id": "m-0"},
        },
        {
            "index": 2,
            "nodeId": "send-mail",
            "instanceKey": "",
            "frame": "enrich",
            "kind": "action",
            "status": "completed",
        },
    ],
    "loops": [
        {
            "nodeId": "notify",
            "instanceKey": "",
            "count": 2,
            "completed": 1,
            "running": 1,
            "nextIndex": 2,
            "status": "running",
        }
    ],
    "frames": [{"key": "enrich", "workflow": "notify-customer@1.0.0", "callNode": "enrich", "status": "completed"}],
    "selectedScope": {"item": {"id": "o-2"}, "index": 1, "loops": {}},
    "blocked": {
        "reason": "missing_mock",
        "nodeId": "notify",
        "instanceKey": "",
        "message": "Step notify needs test data",
    },
    "variables": {"status": "running", "steps": {}, "branches": {}},
    "diagnostics": [],
}


def test_the_execute_example_parses():
    request = lc.ExecuteRequest.model_validate_json(json.dumps(EXECUTE_REQUEST))
    assert request.target.instanceKey == "send[1]"
    assert request.scripts.aiTurns["support"].turns == [{"result": {"text": "Shipped."}}]


def test_the_response_example_round_trips_with_absent_fields_left_out():
    response = lc.ExecuteResponse.model_validate_json(json.dumps(EXECUTE_RESPONSE))
    assert response.model_dump(mode="json", by_alias=True, exclude_unset=True) == EXECUTE_RESPONSE


@pytest.mark.parametrize(
    "target",
    [
        {"mode": "workflow", "stepId": "send"},
        {"mode": "step"},
        {"mode": "before", "instanceKey": "send[1]"},
        {"mode": "step", "stepId": "send", "instanceKey": "notify[1]"},
        {"mode": "step", "stepId": "send", "instanceKey": "send[01]"},
    ],
)
def test_a_target_names_one_step_and_only_its_instances(target):
    with pytest.raises(ValidationError):
        lc.ExecuteRequest.model_validate_json(json.dumps({**EXECUTE_REQUEST, "target": target}))


@pytest.mark.parametrize("case", STEP_KEYS, ids=lambda case: repr(case["key"]))
def test_targets_trace_entries_and_mocks_take_every_shared_key_of_their_step(case):
    target = {"mode": "step", "stepId": case["node_id"], "instanceKey": case["key"]}
    entry = {"index": 0, "nodeId": case["node_id"], "instanceKey": case["view"]["instance_key"]}
    request = {**EXECUTE_REQUEST, "target": target, "mocks": {f"node:{case['key']}": {}}}
    assert lc.ExecuteRequest.model_validate_json(json.dumps(request)).target.instanceKey == case["key"]
    trace = lc.TraceEntry.model_validate_json(json.dumps({**entry, "kind": "action", "status": "completed"}))
    assert trace.instanceKey == case["view"]["instance_key"]


@pytest.mark.parametrize("case", SHARED_KEYS["invalid"], ids=lambda case: repr(case["key"]))
def test_targets_and_mock_keys_refuse_every_shared_non_canonical_key(case):
    for body in (
        {**EXECUTE_REQUEST, "target": {"mode": "step", "stepId": "send", "instanceKey": case["key"]}},
        {**EXECUTE_REQUEST, "mocks": {f"node:{case['key']}": {}}},
    ):
        with pytest.raises(ValidationError):
            lc.ExecuteRequest.model_validate_json(json.dumps(body))


@pytest.mark.parametrize(
    ("key", "valid"),
    [
        ("node:send[1]", True),
        ("node:check", True),
        ("action:crm.lookup@1.0.0", True),
        ("agent:support", True),
        ("tool:support/lookup_order", True),
        ("send", False),
        ("node:", False),
        ("action:crm.lookup", False),
        ("tool:support/1lookup", False),
    ],
)
def test_mock_keys_follow_the_simulator_precedence_kinds(key, valid):
    body = json.dumps({**EXECUTE_REQUEST, "mocks": {key: {}}})
    if valid:
        lc.ExecuteRequest.model_validate_json(body)
    else:
        with pytest.raises(ValidationError):
            lc.ExecuteRequest.model_validate_json(body)


@pytest.mark.parametrize(
    "change",
    [
        {"status": "completed"},
        {"blocked": None},
        {"compile": {"ok": False, "sliced": False, "diagnostics": [], "stubs": []}},
        {
            "trace": [
                {"index": 0, "nodeId": "send", "instanceKey": "notify[0]", "kind": "action", "status": "completed"}
            ]
        },
        {"trace": [{"index": 0, "nodeId": "send", "instanceKey": "send", "kind": "action", "status": "completed"}]},
    ],
)
def test_a_response_states_one_outcome(change):
    with pytest.raises(ValidationError):
        lc.ExecuteResponse.model_validate_json(json.dumps({**EXECUTE_RESPONSE, **change}))


def _without(body: dict, key: str) -> dict:
    return {name: value for name, value in body.items() if name != key}


@pytest.mark.parametrize(
    ("model", "body", "missing"),
    [
        (lc.ExecuteResponse, _without(EXECUTE_RESPONSE, "trace"), "trace"),
        (lc.CompileSummary, _without(EXECUTE_RESPONSE["compile"], "diagnostics"), "diagnostics"),
        (lc.CompileSummary, _without(EXECUTE_RESPONSE["compile"], "stubs"), "stubs"),
    ],
    ids=["response-without-trace", "compile-without-diagnostics", "compile-without-stubs"],
)
def test_a_response_always_reports_its_trace_and_a_compile_summary_its_lists(model, body, missing):
    with pytest.raises(ValidationError) as refused:
        model.model_validate_json(json.dumps(body))
    assert [(error["type"], error["loc"]) for error in refused.value.errors()] == [("missing", (missing,))]


def test_a_callee_source_comes_with_its_format():
    with pytest.raises(ValidationError):
        lc.CalleeSource.model_validate_json(json.dumps({"source": "kind: Workflow"}))
    assert lc.CalleeSource.model_validate_json(json.dumps({"mocks": {"node:send-mail": {"id": "m-9"}}}))


def test_test_data_checks_name_a_code_only_for_refused_entries():
    result = lc.CheckTestDataResult.model_validate_json(
        json.dumps(
            {
                "entries": [
                    {"path": "/pins/check", "ok": True},
                    {"path": "/input/value", "ok": False, "code": "WV-SCHEMA-SECRET_VALUE"},
                ]
            }
        )
    )
    assert [entry.ok for entry in result.entries] == [True, False]
    for entry in (
        {"path": "/pins/check", "ok": True, "code": "WV-SCHEMA-SECRET_VALUE"},
        {"path": "/pins/check", "ok": False},
    ):
        with pytest.raises(ValidationError):
            lc.CheckTestDataEntry.model_validate_json(json.dumps(entry))


def test_a_check_request_carries_a_whole_test_data_document():
    body = {
        "source": "kind: Workflow",
        "format": "yaml",
        "catalog": "none",
        "testData": {"schemaVersion": 1, "kind": "weave.studio/testData", "updatedAt": "2026-10-07T10:00:00Z"},
    }
    assert lc.CheckTestDataRequest.model_validate_json(json.dumps(body)).testData.schema_version == 1


def test_decision_evaluation_takes_a_local_table():
    table = {
        "apiVersion": "weave/v1alpha1",
        "kind": "DecisionTable",
        "metadata": {"name": "payment-policy", "version": "1.3.0"},
        "spec": {
            "inputSchema": {"type": "object", "properties": {"amount": {"type": "number"}}},
            "outputSchema": {"type": "string"},
            "hitPolicy": "first",
            "rules": [{"id": "all", "when": {"literal": True}, "output": {"literal": "approve"}}],
        },
    }
    request = lc.DecisionEvaluateRequest.model_validate_json(json.dumps({"table": table, "input": {"amount": 10}}))
    assert request.table.metadata.version == "1.3.0"


HOST_BODIES = [
    lc.CalleeSource,
    lc.ExecuteScripts,
    lc.ExecuteTarget,
    lc.SimulationRequest,
    lc.ExecuteRequest,
    lc.CompileSummary,
    lc.TraceEntry,
    lc.LoopProgress,
    lc.FrameView,
    lc.LoopRoot,
    lc.SelectedScope,
    lc.Blocked,
    lc.ExecuteResponse,
    lc.CheckTestDataRequest,
    lc.CheckTestDataEntry,
    lc.CheckTestDataResult,
    lc.DecisionEvaluateRequest,
]


def test_host_bodies_are_camel_case():
    for model in HOST_BODIES:
        for name, field in model.model_fields.items():
            assert re.fullmatch(r"[a-z]+(?:[A-Z][a-z0-9]*)*", field.alias or name), (model.__name__, name)
