# Copyright 2026 Firefly Software Foundation.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# Author: Firefly Software Foundation
# SPDX-License-Identifier: Apache-2.0

"""The test-data JSON Schema and its Pydantic models accept exactly the same documents."""

import copy
import json
import re
from datetime import UTC, datetime
from pathlib import Path

import pytest
from hypothesis import given, settings
from hypothesis import strategies as st
from jsonschema import Draft202012Validator, validators
from jsonschema.exceptions import ValidationError as SchemaViolation
from pydantic import TypeAdapter, ValidationError

from firefly_weave.contracts import studio_documents as documents
from firefly_weave.contracts.instance_keys import InstanceKey, InstanceKeyText, format_instance
from firefly_weave.contracts.values import MAX_SAFE_INTEGER

FULL_EXAMPLE = {
    "schemaVersion": 1,
    "kind": "weave.studio/testData",
    "updatedAt": "2026-10-07T10:00:00Z",
    "input": {"value": {"customerId": "c-1", "orders": [{"id": "o-1"}, {"id": "o-2"}]}, "source": "manual"},
    "pins": {
        "check-customer": {
            "output": {"eligible": True},
            "source": "test-call",
            "pinnedAt": "2026-10-07T10:01:00Z",
            "configHash": "fnv1a64:0123456789abcdef",
            "contractHash": "fnv1a64:1111111111111111",
            "upstreamHash": "fnv1a64:fedcba9876543210",
            "runId": "3f2a6c1e-0d5b-4a63-9c1f-2b7e8d9a0b11",
            "runEnvironmentId": "9b1c2d3e-4f50-4a61-8b72-c3d4e5f60718",
        },
        "send": {
            "output": {"id": "m-0"},
            "source": "manual",
            "pinnedAt": "2026-10-07T10:02:00Z",
            "configHash": "fnv1a64:aaaaaaaaaaaaaaaa",
            "contractHash": "fnv1a64:bbbbbbbbbbbbbbbb",
            "upstreamHash": "fnv1a64:cccccccccccccccc",
        },
        "send[1]": {
            "output": {"id": "m-1"},
            "source": "manual",
            "pinnedAt": "2026-10-07T10:02:00Z",
            "configHash": "fnv1a64:aaaaaaaaaaaaaaaa",
            "contractHash": "fnv1a64:bbbbbbbbbbbbbbbb",
            "upstreamHash": "fnv1a64:cccccccccccccccc",
        },
    },
    "signals": {"wait-paid": {"payload": {"paid": True}, "afterSeconds": 60}},
    "humans": {
        "approval": {"decision": "approve", "data": {}},
        "review": {"decision": "reject", "data": {"note": "Wrong address"}, "frame": "enrich"},
    },
    "aiTurns": {
        "support": {"turns": [{"result": {"text": "Your order shipped."}}], "autoApprove": True, "source": "manual"}
    },
    "workflows": {"notify-customer@1.0.0": {"mocks": {"send-mail": {"output": {"id": "m-9"}, "source": "manual"}}}},
    "waits": {"autoAdvance": True},
}
MINIMAL = {"schemaVersion": 1, "kind": "weave.studio/testData", "updatedAt": "2026-10-07T10:00:00Z"}
PIN = FULL_EXAMPLE["pins"]["send"]
RUN_ID = "3f2a6c1e-0d5b-4a63-9c1f-2b7e8d9a0b11"
ENVIRONMENT_ID = "9b1c2d3e-4f50-4a61-8b72-c3d4e5f60718"
# The shared instance-key cases, generated by scripts/language_fixtures.py from firefly_weave.contracts.instance_keys.
SHARED_KEYS = json.loads(
    (Path(__file__).resolve().parents[2] / "studio/tests/fixtures/language/instance-keys.json").read_text("utf-8")
)


def doc(**fields):
    return {**copy.deepcopy(MINIMAL), **copy.deepcopy(fields)}


def ecmascript_pattern(validator, pattern, instance, schema):
    """JSON Schema patterns are ECMAScript: a final "$" matches only at the end, not before a trailing newline."""
    if validator.is_type(instance, "string") and re.search(re.sub(r"(?<!\\)\$$", r"\\Z", pattern), instance) is None:
        yield SchemaViolation(f"{instance!r} does not match {pattern!r}")


EcmaScriptValidator = validators.extend(Draft202012Validator, {"pattern": ecmascript_pattern})


def schema_accepts(document) -> bool:
    validator = EcmaScriptValidator(
        documents.studio_test_data_schema(), format_checker=Draft202012Validator.FORMAT_CHECKER
    )
    return validator.is_valid(document)


def model_accepts(document) -> bool:
    try:
        documents.parse_test_data(json.dumps(document).encode())
    except ValidationError:
        return False
    return True


CASES = [
    ("the full example", FULL_EXAMPLE, True),
    ("only the required fields", MINIMAL, True),
    (
        "a signal that times out in a sub-workflow frame",
        doc(signals={"wait-paid": {"outcome": "timeout", "frame": "notify[2]/enrich"}}),
        True,
    ),
    ("a human task that expires", doc(humans={"approval": {"outcome": "expire"}}), True),
    (
        "AI turns with memory and fingerprints",
        doc(
            aiTurns={
                "support#2": {
                    "turns": [{"final": {"text": "ok"}}],
                    "memory": [{"role": "user", "content": "hi"}],
                    "configHash": "fnv1a64:0123456789abcdef",
                    "upstreamHash": "fnv1a64:0123456789abcdef",
                    "source": "manual",
                }
            }
        ),
        True,
    ),
    ("a client-asserted containsRunData flag", doc(containsRunData=False), False),
    ("schema version 2", {**MINIMAL, "schemaVersion": 2}, False),
    ("a pin without contractHash", doc(pins={"send": {k: v for k, v in PIN.items() if k != "contractHash"}}), False),
    ("a fingerprint without its prefix", doc(pins={"send": {**PIN, "configHash": "0123456789abcdef"}}), False),
    (
        "run data without runId",
        doc(input={"value": 1, "source": "run", "runEnvironmentId": "9b1c2d3e-4f50-4a61-8b72-c3d4e5f60718"}),
        False,
    ),
    (
        "runId without runEnvironmentId",
        doc(input={"value": 1, "source": "manual", "runId": "3f2a6c1e-0d5b-4a63-9c1f-2b7e8d9a0b11"}),
        False,
    ),
    ("an index with a leading zero", doc(pins={"send[01]": PIN}), False),
    ("a bracket in the step ID", doc(pins={"send]3[": PIN}), False),
    ("a zero yield count", doc(pins={"notify~0": PIN}), False),
    ("an empty activation segment", doc(pins={"support#": PIN}), False),
    (
        "a frame with a trailing slash",
        doc(humans={"review": {"decision": "approve", "data": {}, "frame": "notify[2]/"}}),
        False,
    ),
    ("a callee without a version", doc(workflows={"notify-customer": {"mocks": {}}}), False),
    (
        "a system memory message",
        doc(aiTurns={"support": {"turns": [], "memory": [{"role": "system", "content": "x"}]}}),
        False,
    ),
    (
        "a signal with a payload and an outcome",
        doc(signals={"wait-paid": {"payload": {}, "outcome": "timeout"}}),
        False,
    ),
    ("more than 100 AI turns", doc(aiTurns={"support": {"turns": [{"final": {}}] * 101}}), False),
    ("a timestamp without a time zone", {**MINIMAL, "updatedAt": "2026-10-07T10:00:00"}, False),
    ("more than 1000 pins", doc(pins={f"step-{i}": PIN for i in range(1001)}), False),
    # A JSON null never stands for an omitted field; data values (payload, data, output, value) may be null.
    ("a null input", doc(input=None), False),
    ("a null pins map", doc(pins=None), False),
    ("a null auto-advance flag", doc(waits={"autoAdvance": None}), False),
    ("a null waits object", doc(waits=None), False),
    ("a null frame", doc(humans={"review": {"decision": "approve", "data": {}, "frame": None}}), False),
    ("a null delay", doc(signals={"wait-paid": {"payload": 1, "afterSeconds": None}}), False),
    ("a null run identifier", doc(input={"value": 1, "source": "manual", "runId": None}), False),
    ("null AI memory", doc(aiTurns={"support": {"turns": [], "memory": None}}), False),
    (
        "null data values",
        doc(
            input={"value": None, "source": "manual"},
            signals={"wait-paid": {"payload": None}},
            humans={"approval": {"decision": "approve", "data": None}},
            workflows={"notify-customer@1.0.0": {"mocks": {"send-mail": {"output": None, "source": "manual"}}}},
        ),
        True,
    ),
    # Field names are the camelCase aliases only; the Python names are for code that builds a model.
    (
        "snake_case top-level names",
        {"schema_version": 1, "kind": "weave.studio/testData", "updated_at": "2026-10-07T10:00:00Z"},
        False,
    ),
    (
        "a snake_case pin field",
        doc(pins={"send": {**{k: v for k, v in PIN.items() if k != "pinnedAt"}, "pinned_at": PIN["pinnedAt"]}}),
        False,
    ),
    ("a snake_case name beside its alias", {**MINIMAL, "schema_version": 1}, False),
    ("a snake_case pin field beside its alias", doc(pins={"send": {**PIN, "pinned_at": PIN["pinnedAt"]}}), False),
    (
        "snake_case run identifiers",
        doc(input={"value": 1, "source": "run", "run_id": RUN_ID, "run_environment_id": ENVIRONMENT_ID}),
        False,
    ),
    # UUIDs are hyphenated, in either case.
    (
        "canonical UUIDs and timestamps in other spellings",
        doc(
            input={"value": 1, "source": "run", "runId": RUN_ID.upper(), "runEnvironmentId": ENVIRONMENT_ID},
            signals={"wait-paid": {"payload": 1}},
            pins={"send": {**PIN, "pinnedAt": "2026-10-07T12:00:00.123456+02:00"}},
        ),
        True,
    ),
    (
        "an un-hyphenated run identifier",
        doc(input={"value": 1, "source": "run", "runId": RUN_ID.replace("-", ""), "runEnvironmentId": ENVIRONMENT_ID}),
        False,
    ),
    (
        "a braced run identifier",
        doc(input={"value": 1, "source": "run", "runId": "{" + RUN_ID + "}", "runEnvironmentId": ENVIRONMENT_ID}),
        False,
    ),
    (
        "a urn run environment identifier",
        doc(input={"value": 1, "source": "run", "runId": RUN_ID, "runEnvironmentId": "urn:uuid:" + ENVIRONMENT_ID}),
        False,
    ),
    # Timestamps are RFC 3339 date-times.
    ("a timestamp with a space instead of T", {**MINIMAL, "updatedAt": "2026-10-07 10:00:00Z"}, False),
    ("a timestamp with an offset without a colon", {**MINIMAL, "updatedAt": "2026-10-07T10:00:00+0000"}, False),
    ("a pin timestamp without seconds", doc(pins={"send": {**PIN, "pinnedAt": "2026-10-07T10:02Z"}}), False),
    ("a boolean schema version", {**MINIMAL, "schemaVersion": True}, False),
]


@pytest.mark.parametrize(("document", "valid"), [case[1:] for case in CASES], ids=[case[0] for case in CASES])
def test_schema_and_models_accept_the_same_documents(document, valid):
    assert schema_accepts(document) is valid
    assert model_accepts(document) is valid


def test_the_full_example_round_trips_without_adding_or_dropping_fields():
    parsed = documents.parse_test_data(json.dumps(FULL_EXAMPLE).encode())
    assert parsed.model_dump(mode="json", by_alias=True) == FULL_EXAMPLE


def test_python_code_may_build_a_model_by_field_name_but_json_may_not():
    built = documents.StudioTestData(
        schema_version=1, kind="weave.studio/testData", updated_at=datetime(2026, 10, 7, 10, tzinfo=UTC)
    )
    assert built.model_dump(mode="json", by_alias=True) == MINIMAL
    with pytest.raises(ValidationError):
        documents.parse_test_data(json.dumps({"schema_version": 1, **MINIMAL}).encode())


def test_schema_patterns_are_the_module_patterns():
    schema = documents.studio_test_data_schema()
    assert schema["$id"] == documents.TEST_DATA_SCHEMA_ID
    key = {name: value for name, value in schema["$defs"]["key"].items() if name != "$comment"}
    assert key == TypeAdapter(InstanceKeyText).json_schema()
    assert schema["$defs"]["frame"]["pattern"] == documents.FRAME_PATTERN
    assert schema["$defs"]["reference"]["pattern"] == documents.REFERENCE_PATTERN
    assert schema["$defs"]["hash"]["pattern"] == documents.HASH_PATTERN


@pytest.mark.parametrize(
    ("key", "valid"),
    [(case["key"], True) for case in SHARED_KEYS["valid"]] + [(case["key"], False) for case in SHARED_KEYS["invalid"]],
    ids=repr,
)
def test_keys_are_exactly_the_shared_instance_keys(key, valid):
    mocks = {"notify-customer@1.0.0": {"mocks": {key: {"output": None, "source": "manual"}}}}
    document = doc(pins={key: PIN}, workflows=mocks)
    assert schema_accepts(document) is valid
    assert model_accepts(document) is valid


instance_keys = st.builds(
    InstanceKey,
    st.from_regex(r"[A-Za-z0-9][A-Za-z0-9_.-]{0,15}", fullmatch=True),
    st.lists(st.integers(0, MAX_SAFE_INTEGER), max_size=3).map(tuple),
    st.lists(st.from_regex(r"[A-Za-z0-9]{1,4}", fullmatch=True), max_size=3).map(tuple),
    st.none() | st.integers(1, MAX_SAFE_INTEGER),
).map(format_instance)


@settings(max_examples=200, deadline=None)
@given(instance_keys)
def test_every_instance_key_of_the_grammar_is_a_test_data_key(key):
    assert schema_accepts(doc(pins={key: PIN}))
    assert model_accepts(doc(pins={key: PIN}))


def test_a_document_over_one_mebibyte_is_refused_before_parsing():
    with pytest.raises(documents.StudioDocumentTooLarge):
        documents.parse_test_data(b" " * (documents.TEST_DATA_MAX_BYTES + 1))
    assert documents.parse_test_data(json.dumps(FULL_EXAMPLE).encode()).pins is not None


ENVELOPE = {
    "draft_id": "0f8f2a10-3c4d-4e5f-8a9b-1c2d3e4f5a6b",
    "kind": "test-data",
    "revision": 3,
    "draft_revision": 12,
    "document": FULL_EXAMPLE,
    "contains_run_data": True,
    "source_environment_ids": ["9b1c2d3e-4f50-4a61-8b72-c3d4e5f60718"],
    "updated_at": "2026-10-07T10:05:00Z",
    "updated_by": "5d6e7f80-1a2b-4c3d-8e9f-0a1b2c3d4e5f",
}


def test_the_envelope_is_snake_case_and_keeps_the_document_casing():
    envelope = documents.StudioDocument.model_validate_json(json.dumps(ENVELOPE))
    assert envelope.model_dump(mode="json") == ENVELOPE


@pytest.mark.parametrize("claim", [{"contains_run_data": False}, {"source_environment_ids": []}])
def test_a_save_cannot_assert_or_clear_run_data(claim):
    with pytest.raises(ValidationError):
        documents.StudioDocumentSave.model_validate_json(
            json.dumps({"draft_revision": 12, "document": MINIMAL, **claim})
        )
    assert documents.StudioDocumentSave.model_validate_json(json.dumps({"draft_revision": 12, "document": MINIMAL}))


def test_document_kinds_and_size_limits():
    assert documents.STUDIO_DOCUMENT_MAX_BYTES == {"canvas": 262_144, "test-data": 1_048_576}
    with pytest.raises(ValidationError):
        documents.StudioDocument.model_validate_json(json.dumps({**ENVELOPE, "kind": "layout"}))


def test_sidecar_fields_are_camel_case_on_the_wire():
    models = [
        documents.StudioTestData,
        documents.InputEntry,
        documents.PinEntry,
        documents.MockEntry,
        documents.SignalScript,
        documents.SignalTimeout,
        documents.HumanScript,
        documents.HumanExpire,
        documents.AiTurnsEntry,
        documents.AiMemoryMessage,
        documents.CalleeMocks,
        documents.WaitScripts,
    ]
    for model in models:
        for name, field in model.model_fields.items():
            assert re.fullmatch(r"[a-z]+(?:[A-Z][a-z0-9]*)*", field.alias or name), (model.__name__, name)
